#ifndef COCOA_WAYLAND_CURSOR_CONFIG_H
#define COCOA_WAYLAND_CURSOR_CONFIG_H

#define HAVE_MEMFD_CREATE 1
#define HAVE_MKOSTEMP 1
#define HAVE_POSIX_FALLOCATE 1

#endif //COCOA_WAYLAND_CURSOR_CONFIG_H
