/**
 * This file is part of Cocoa.
 *
 * Cocoa is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Cocoa is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Cocoa. If not, see <https://www.gnu.org/licenses/>.
 */

import { GskNode, GskConcreteType, GskInvalidationRecorder, GskHitTestableNode } from './GskNode';
import { Vec2, Rect, Mat3x3 } from 'renderer';
import { Maybe } from '../../core/error';
import { GskRenderNode, RenderContext } from './GskRenderNode';
import { GskDLRecorder } from './GskDisplayList';
import { Scene } from 'present';

/**
 * A helper class that transforms a DisplayList generated by a GskRenderNode
 * into a native scene object (a `Scene` object from `glamor` native module).
 * The scene object can be used to render on a window using `Surface.contentAggregator`.
 *
 * Note that this node ignores the CTM given by the `revalidate()` call, and sets
 * it to an identity matrix for its child node.
 */
export class GskPipelineNativeSceneRaster extends GskNode implements GskHitTestableNode<GskRenderNode> {
    private readonly fChild: GskRenderNode;

    constructor(child: GskRenderNode) {
        super(GskConcreteType.kPipelineNativeSceneRaster, 0);
        this.fChild = child;
        this.observeChild(this.fChild);
    }

    protected onRevalidate(recorder: GskInvalidationRecorder): Rect {
        return this.fChild.revalidate(recorder, Mat3x3.Identity());
    }

    public raster(viewportCull: Rect): Scene {
        this.ASSERT_REVALIDATED();
        const dl = new GskDLRecorder(viewportCull);

        // A default RenderContext is created as no toplevel transformations
        // are needed.
        const renderContext = new RenderContext();
        this.fChild.render(dl, renderContext);

        dl.finalize();

        return null;
        // return dl.build();
    }

    public nodeAt(point: Vec2): Maybe<GskRenderNode> {
        return this.fChild.nodeAt(point);
    }
}
