#include <vector>
#include <variant>
#include <unordered_map>
#include <sstream>

#include "fmt/format.h"

#include "Core/Errors.h"
#include "Gallium/bindings/cobalt/Exports.h"
#include "Gallium/bindings/core/Exports.h"
#include "Gallium/binder/Class.h"

#include "include/core/SkPaint.h"
#include "include/core/SkPath.h"
#include "include/core/SkM44.h"
#include "include/core/SkPicture.h"
#include "include/core/SkPictureRecorder.h"
#include "include/core/SkBlender.h"
#include "include/core/SkShader.h"
#include "include/core/SkColorFilter.h"
#include "include/core/SkMaskFilter.h"
#include "include/core/SkImageFilter.h"
#include "include/core/SkPathEffect.h"

#include "include/effects/SkBlenders.h"
#include "include/effects/SkGradientShader.h"
#include "include/effects/SkPerlinNoiseShader.h"
GALLIUM_BINDINGS_COBALT_NS_BEGIN

#define VERB_OPCODE(x)      ((x) & 0xff)
#define VERB_N_ARGS(x)      ((x) >> 8)

class IRStreamReader
{
public:
    explicit IRStreamReader(std::vector<Buffer*>&& buffers);

    template<typename T>
    T extractNext();

    uint16_t fetchNextVerb();
    void switchNextBuffer();

    gal_nodiscard inline int32_t getBufferIndex() const {
        return buffer_index_;
    }

    gal_nodiscard inline uint8_t *getBufferReadPtr() const {
        return buffer_rdptr_;
    }

    gal_nodiscard inline off_t getBufferReadOffset() const {
        return buffer_rdptr_ - buffers_[buffer_index_]->getWriteableDataPointerByte();
    }

private:
    std::vector<Buffer*>    buffers_;
    int32_t                 buffer_index_;
    uint8_t                *buffer_rdptr_;
    uint8_t                *buffer_endptr_;
};

class IRHeap
{
public:
    using U32Array = std::vector<uint32_t>;
    using F32Array = std::vector<float>;

    struct Cell
    {
        enum class Typeinfo
        {
            kMismatch,
            kU32Array,
            kF32Array,
            kMatrix4x4,
            kVector2,
            kVector3,
            kVector4,
            kRect,
            kPaint,
            kPath,
            kSpShader,
            kSpBlender,
            kSpColorFilter,
            kSpImageFilter,
            kSpMaskFilter,
            kSpPathEffect
        };

        union ObjectSizeMeasurerUnion
        {
            gal_maybe_unsed U32Array v_u32_array;
            gal_maybe_unsed F32Array v_f32_array;
            gal_maybe_unsed SkM44 v_matrix_4x4;
            gal_maybe_unsed SkV2 v_vector2;
            gal_maybe_unsed SkV3 v_vector3;
            gal_maybe_unsed SkV4 v_vector4;
            gal_maybe_unsed SkRect v_rect;
            gal_maybe_unsed SkPaint v_paint;
            gal_maybe_unsed SkPath v_path;
            gal_maybe_unsed sk_sp<SkShader> v_sp_shader;
            gal_maybe_unsed sk_sp<SkBlender> v_sp_blender;
            gal_maybe_unsed sk_sp<SkColorFilter> v_sp_color_filter;
            gal_maybe_unsed sk_sp<SkImageFilter> v_sp_image_filter;
            gal_maybe_unsed sk_sp<SkMaskFilter> v_sp_mask_filter;
            gal_maybe_unsed sk_sp<SkPathEffect> v_sp_path_effect;
        };

        template<typename T, typename...ArgsT>
        explicit Cell(T *placeholder, ArgsT&&...args);

        Cell(const Cell& lhs) noexcept;

        ~Cell();

        Typeinfo        typeinfo_;
        uint8_t         stored_[sizeof(ObjectSizeMeasurerUnion)];
    };

    struct Profile
    {
        size_t      heap_total_size = 0;
        size_t      heap_cell_size = 0;
        uint32_t    allocation_count = 0;
        uint32_t    extraction_count = 0;
        size_t      leaked_cells = 0;
    };

    IRHeap();
    ~IRHeap() = default;

    template<typename T, typename...ArgsT>
    void allocate(uint32_t key, ArgsT&&...args);

    template<typename T>
    T& extract(uint32_t key);

    void cloneCell(uint32_t from, uint32_t key);

    void free(uint32_t key);

    void profile(Profile& out);

private:
    std::unordered_map<uint32_t, std::unique_ptr<Cell>> cells_map_;
    Profile profile_;
};

// This file is generated by script/vrir-opcodes-codegen.py
// in ${CMAKE_CURRENT_BINARY_DIR}
#include <VRIROpcodeGenerated.hpp>

IRStreamReader::IRStreamReader(std::vector<Buffer *>&& buffers)
        : buffers_(buffers)
        , buffer_index_(0)
{
    buffer_rdptr_ = buffers_[0]->getWriteableDataPointerByte();
    buffer_endptr_ = buffer_rdptr_ + buffers[0]->length();
}

template<typename T>
T IRStreamReader::extractNext()
{
    if (buffer_rdptr_ + sizeof(T) > buffer_endptr_)
        g_throw(Error, "Corrupted serialize IR buffer: reading out of buffer");
    buffer_rdptr_ += sizeof(T);
    return *reinterpret_cast<T*>(buffer_rdptr_ - sizeof(T));
}

uint16_t IRStreamReader::fetchNextVerb()
{
    if (buffer_rdptr_ >= buffer_endptr_)
        g_throw(Error, "Corrupted serialized IR buffer");

    auto verb = extractNext<uint16_t>();
    if (VERB_OPCODE(verb) == opcode::kSwitchNextBuffer)
    {
        switchNextBuffer();
        // TODO: Eliminate this recursive chain
        return fetchNextVerb();
    }
    return verb;
}

void IRStreamReader::switchNextBuffer()
{
    buffer_index_++;
    if (buffer_index_ >= buffers_.size())
        g_throw(Error, "[SwitchNextBuffer] direct us to an invalid buffer");
    buffer_rdptr_ = buffers_[buffer_index_]->getWriteableDataPointerByte();
    buffer_endptr_ = buffer_rdptr_ + buffers_[buffer_index_]->length();
}

template<typename T>
constexpr IRHeap::Cell::Typeinfo typeinfo_from_type() {
    return IRHeap::Cell::Typeinfo::kMismatch;
}

#define GEN_TYPEINFO_FROM_TYPE(type, typeinfo)                              \
template<>                                                                  \
constexpr IRHeap::Cell::Typeinfo typeinfo_from_type<type>() {  \
    return IRHeap::Cell::Typeinfo::k##typeinfo;                \
}

GEN_TYPEINFO_FROM_TYPE(IRHeap::U32Array, U32Array)
GEN_TYPEINFO_FROM_TYPE(IRHeap::F32Array, F32Array)
GEN_TYPEINFO_FROM_TYPE(SkM44, Matrix4x4)
GEN_TYPEINFO_FROM_TYPE(SkV2, Vector2)
GEN_TYPEINFO_FROM_TYPE(SkV3, Vector3)
GEN_TYPEINFO_FROM_TYPE(SkV4, Vector4)
GEN_TYPEINFO_FROM_TYPE(SkRect, Rect)
GEN_TYPEINFO_FROM_TYPE(SkPaint, Paint)
GEN_TYPEINFO_FROM_TYPE(SkPath, Path)
GEN_TYPEINFO_FROM_TYPE(sk_sp<SkShader>, SpShader)
GEN_TYPEINFO_FROM_TYPE(sk_sp<SkBlender>, SpBlender)
GEN_TYPEINFO_FROM_TYPE(sk_sp<SkColorFilter>, SpColorFilter)
GEN_TYPEINFO_FROM_TYPE(sk_sp<SkImageFilter>, SpImageFilter)
GEN_TYPEINFO_FROM_TYPE(sk_sp<SkMaskFilter>, SpMaskFilter)
GEN_TYPEINFO_FROM_TYPE(sk_sp<SkPathEffect>, SpPathEffect)

#undef GEN_TYPEINFO_FROM_TYPE

template<typename T, typename...ArgsT>
IRHeap::Cell::Cell(gal_maybe_unsed T *placeholder, ArgsT&& ...args)
    : typeinfo_(typeinfo_from_type<T>())
    , stored_{}
{
    constexpr Typeinfo typeinfo = typeinfo_from_type<T>();
    static_assert(typeinfo != Typeinfo::kMismatch, "typecheck: invalid type to construct Cell");
    new (static_cast<void*>(&stored_[0])) T(std::forward<ArgsT>(args)...);
}

#define CLONE_TYPE(t) new (static_cast<void*>(&stored_[0])) t(*reinterpret_cast<const t*>(&lhs.stored_[0]))
IRHeap::Cell::Cell(const Cell& lhs) noexcept
    : typeinfo_(lhs.typeinfo_)
    , stored_{}
{
    switch (typeinfo_)
    {
    case Typeinfo::kU32Array:   CLONE_TYPE(U32Array); break;
    case Typeinfo::kF32Array:   CLONE_TYPE(F32Array); break;
    case Typeinfo::kMatrix4x4:  CLONE_TYPE(SkM44); break;
    case Typeinfo::kVector2:    CLONE_TYPE(SkV2);  break;
    case Typeinfo::kVector3:    CLONE_TYPE(SkV3);  break;
    case Typeinfo::kVector4:    CLONE_TYPE(SkV4);  break;
    case Typeinfo::kRect:       CLONE_TYPE(SkRect);  break;
    case Typeinfo::kPaint:      CLONE_TYPE(SkPaint); break;
    case Typeinfo::kPath:       CLONE_TYPE(SkPath); break;
    case Typeinfo::kSpShader:   CLONE_TYPE(sk_sp<SkShader>); break;
    case Typeinfo::kSpBlender:  CLONE_TYPE(sk_sp<SkBlender>); break;
    case Typeinfo::kSpColorFilter:   CLONE_TYPE(sk_sp<SkColorFilter>); break;
    case Typeinfo::kSpImageFilter:   CLONE_TYPE(sk_sp<SkImageFilter>); break;
    case Typeinfo::kSpMaskFilter:    CLONE_TYPE(sk_sp<SkMaskFilter>); break;
    case Typeinfo::kSpPathEffect:    CLONE_TYPE(sk_sp<SkPathEffect>); break;
    default:
        MARK_UNREACHABLE("Invalid typeinfo for cell: could not clone object properly");
    }
}
#undef CLONE_TYPE

IRHeap::Cell::~Cell()
{
#define DESTRUCT_TYPE(type) reinterpret_cast<type *>(&stored_[0])->~type()
#define DESTRUCT_TYPE2(type, dtor) reinterpret_cast<type *>(&stored_[0])->dtor()
    switch (typeinfo_)
    {
    case Typeinfo::kU32Array:   DESTRUCT_TYPE(U32Array); break;
    case Typeinfo::kF32Array:   DESTRUCT_TYPE(F32Array); break;
    case Typeinfo::kMatrix4x4:  DESTRUCT_TYPE(SkM44); break;
    case Typeinfo::kVector2:    DESTRUCT_TYPE(SkV2); break;
    case Typeinfo::kVector3:    DESTRUCT_TYPE(SkV3); break;
    case Typeinfo::kVector4:    DESTRUCT_TYPE(SkV4); break;
    case Typeinfo::kRect:       DESTRUCT_TYPE(SkRect); break;
    case Typeinfo::kPaint:      DESTRUCT_TYPE(SkPaint); break;
    case Typeinfo::kPath:       DESTRUCT_TYPE(SkPath); break;
    case Typeinfo::kSpShader:   DESTRUCT_TYPE(sk_sp<SkShader>); break;
    case Typeinfo::kSpBlender:  DESTRUCT_TYPE(sk_sp<SkBlender>); break;
    case Typeinfo::kSpColorFilter:   DESTRUCT_TYPE(sk_sp<SkColorFilter>); break;
    case Typeinfo::kSpImageFilter:   DESTRUCT_TYPE(sk_sp<SkImageFilter>); break;
    case Typeinfo::kSpMaskFilter:    DESTRUCT_TYPE(sk_sp<SkMaskFilter>); break;
    case Typeinfo::kSpPathEffect:    DESTRUCT_TYPE(sk_sp<SkPathEffect>); break;
    default:
        MARK_UNREACHABLE("Invalid typeinfo for cell: could not destruct object properly");
    }
#undef DESTRUCT_TYPE
#undef DESTRUCT_TYPE2
}

IRHeap::IRHeap()
{
    profile_.heap_cell_size = sizeof(Cell);
}

template<typename T, typename...ArgsT>
void IRHeap::allocate(uint32_t key, ArgsT&& ...args)
{
    if (cells_map_.count(key) > 0)
        g_throw(Error, fmt::format("Key {} has been used for another heap object", key));

    T *placeholder = nullptr;
    cells_map_.try_emplace(key, new Cell(placeholder, std::forward<ArgsT>(args)...));

    profile_.allocation_count++;
    profile_.heap_total_size += profile_.heap_cell_size;
    profile_.leaked_cells++;
}

template<typename T>
T& IRHeap::extract(uint32_t key)
{
    constexpr Cell::Typeinfo typeinfo = typeinfo_from_type<T>();
    static_assert(typeinfo != IRHeap::Cell::Typeinfo::kMismatch,
                  "typecheck: invalid type to extract from Cell");

    if (cells_map_.count(key) == 0)
        g_throw(Error, fmt::format("Key {} points to an invalid heap object", key));
    std::unique_ptr<Cell>& cell = cells_map_.at(key);

    profile_.extraction_count++;
    return *reinterpret_cast<T*>(&cell->stored_[0]);
}

void IRHeap::cloneCell(uint32_t from, uint32_t key)
{
    if (cells_map_.count(from) == 0)
        g_throw(Error, fmt::format("Key {} points to an invalid heap object", from));
    if (cells_map_.count(key) > 0)
        g_throw(Error, fmt::format("Key {} has been used for another heap object", key));
    cells_map_[key] = std::make_unique<Cell>(*cells_map_[from]);

    profile_.allocation_count++;
    profile_.heap_total_size += profile_.heap_cell_size;
    profile_.leaked_cells++;
}

void IRHeap::free(uint32_t key)
{
    if (cells_map_.count(key) == 0)
        g_throw(Error, fmt::format("Key {} points to an invalid heap object", key));

    cells_map_.erase(key);
    profile_.leaked_cells--;
    profile_.heap_total_size -= profile_.heap_cell_size;
}

void IRHeap::profile(Profile& out)
{
    std::memcpy(&out, &profile_, sizeof(Profile));
}

std::unique_ptr<IRStreamReader> get_ir_stream_reader(v8::Local<v8::Value> array)
{
    v8::Isolate *isolate = v8::Isolate::GetCurrent();
    auto values = binder::from_v8<std::vector<v8::Local<v8::Value>>>(isolate, array);
    std::vector<Buffer*> unwrapped(values.size());

    for (uint32_t i = 0; i < values.size(); i++)
    {
        Buffer *ptr = binder::Class<Buffer>::unwrap_object(isolate, values[i]);
        if (ptr == nullptr)
            g_throw(TypeError, "Expecting an array containing instances of core.Buffer type");
        unwrapped[i] = ptr;
    }

    return std::make_unique<IRStreamReader>(std::move(unwrapped));
}

v8::Local<v8::Value> VRIRCompilerWrap::Compile(v8::Local<v8::Value> array)
{
    std::unique_ptr<IRStreamReader> readerOwned = get_ir_stream_reader(array);
    IRStreamReader& reader = *readerOwned;

    uint16_t verb = reader.fetchNextVerb();
    if (VERB_OPCODE(verb) != opcode::kDrawBounds || VERB_N_ARGS(verb) != 2)
        g_throw(Error, "Requires a [DrawBounds] as the first annotation");

    SkRect drawBounds = SkRect::MakeWH(reader.extractNext<float>(),
                                       reader.extractNext<float>());
    if (drawBounds.width() <= 0 || drawBounds.height() <= 0)
        g_throw(Error, "Annotation [DrawBounds] requires 2 positive f32 numbers");

    SkPictureRecorder recorder;
    SkCanvas *canvas = recorder.beginRecording(drawBounds, SkRTreeFactory()());
    CHECK(canvas);

    IRHeap heap;

    opcode::Dispatch(reader, heap, canvas);

#if 0
    SmallDrawObjectHeap::Profile prof{};
    heap.profile(prof);

    fmt::print("VRIR Execution Heap Profile:\n");
    fmt::print("  cell size: {}\n  total heap size: {}\n", prof.heap_cell_size, prof.heap_total_size);
    fmt::print("  allocations: {}\n  extractions: {}\n", prof.allocation_count, prof.extraction_count);
    fmt::print("  leaked cells: {}\n", prof.leaked_cells);
#endif

    sk_sp<SkPicture> picture = recorder.finishRecordingAsPicture();

    v8::Isolate *isolate = v8::Isolate::GetCurrent();
    return v8::Undefined(isolate);
}

v8::Local<v8::Value> VRIRCompilerWrap::Disassemble(v8::Local<v8::Value> array)
{
    std::unique_ptr<IRStreamReader> readerOwned = get_ir_stream_reader(array);
    IRStreamReader& reader = *readerOwned;

    std::ostringstream stream;
    int32_t cnt = 0;
    do
    {
        off_t offset = reader.getBufferReadOffset();
        int32_t buf = reader.getBufferIndex();
        uint8_t *bufPtr = reader.getBufferReadPtr();

        auto verb = reader.extractNext<uint16_t>();
        const opcode::OpcodeVectorTbl *opv = nullptr;
        for (const auto& element : opcode::g_opcode_vector_tbl)
        {
            if (element.opcode == VERB_OPCODE(verb))
            {
                opv = &element;
                break;
            }
        }
        if (opv == nullptr)
            g_throw(Error, "Illegal VM instruction for disassembling");

        stream << fmt::format("  #{}:{:04d}<+{:04d}:{}>|    {} ", buf, cnt, offset, fmt::ptr(bufPtr), opv->name);

        const auto* opr = &opv->operands[0];
        while (opr->type_name)
        {
            if (opr != &opv->operands[0])
                stream << ", ";
            stream << opr->type_name << ' ';

            switch (static_cast<opcode::OperandTypes>(opr->type_id))
            {
            case opcode::OperandTypes::memop:
                stream << fmt::format("%0x{:x}", reader.extractNext<opcode::MemOp>());
                break;
            case opcode::OperandTypes::u8:
                stream << fmt::format("$0x{:x}", reader.extractNext<uint8_t>());
                break;
            case opcode::OperandTypes::i8:
                stream << fmt::format("$0x{:x}", reader.extractNext<int8_t>());
                break;
            case opcode::OperandTypes::u16:
                stream << fmt::format("$0x{:x}", reader.extractNext<uint16_t>());
                break;
            case opcode::OperandTypes::i16:
                stream << fmt::format("$0x{:x}", reader.extractNext<int16_t>());
                break;
            case opcode::OperandTypes::u32:
                stream << fmt::format("$0x{:x}", reader.extractNext<uint32_t>());
                break;
            case opcode::OperandTypes::i32:
                stream << fmt::format("$0x{:x}", reader.extractNext<int32_t>());
                break;
            case opcode::OperandTypes::u64:
                stream << fmt::format("$0x{:x}", reader.extractNext<uint64_t>());
                break;
            case opcode::OperandTypes::i64:
                stream << fmt::format("$0x{:x}", reader.extractNext<int64_t>());
                break;
            case opcode::OperandTypes::f32:
                stream << fmt::format("${}", reader.extractNext<float>());
                break;
            case opcode::OperandTypes::f64:
                stream << fmt::format("${}", reader.extractNext<double>());
                break;
            }
            opr++;
        }
        stream << '\n';

        if (verb == opcode::kSwitchNextBuffer)
            reader.switchNextBuffer();
        else if (verb == opcode::kCommandPoolEnd)
            break;
    } while (++cnt);

    v8::Isolate *isolate = v8::Isolate::GetCurrent();
    return binder::to_v8(isolate, stream.str());
}
GALLIUM_BINDINGS_COBALT_NS_END
