
var CanvasKitInit = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(CanvasKitInit) {
  CanvasKitInit = CanvasKitInit || {};


null;var p;p||(p=typeof CanvasKitInit !== 'undefined' ? CanvasKitInit : {});var ca,da;p.ready=new Promise(function(a,e){ca=a;da=e});
(function(a){a.bb=a.bb||[];a.bb.push(function(){a.MakeSWCanvasSurface=function(e){var f=e;if("CANVAS"!==f.tagName&&(f=document.getElementById(e),!f))throw"Canvas with id "+e+" was not found";if(e=a.MakeSurface(f.width,f.height))e.yb=f;return e};a.MakeCanvasSurface||(a.MakeCanvasSurface=a.MakeSWCanvasSurface);a.MakeSurface=function(e,f){var h={width:e,height:f,colorType:a.ColorType.RGBA_8888,alphaType:a.AlphaType.Unpremul,colorSpace:a.ColorSpace.SRGB},l=e*f*4,q=a._malloc(l);if(h=a.Surface._makeRasterDirect(h,
q,4*e))h.yb=null,h.Rb=e,h.Ob=f,h.Pb=l,h.Db=q,h.getCanvas().clear(a.TRANSPARENT);return h};a.MakeRasterDirectSurface=function(e,f,h){return a.Surface._makeRasterDirect(e,f.byteOffset,h)};a.Surface.prototype.flush=function(e){this._flush();if(this.yb){var f=new Uint8ClampedArray(a.HEAPU8.buffer,this.Db,this.Pb);f=new ImageData(f,this.Rb,this.Ob);e?this.yb.getContext("2d").putImageData(f,0,0,e[0],e[1],e[2]-e[0],e[3]-e[1]):this.yb.getContext("2d").putImageData(f,0,0)}};a.Surface.prototype.dispose=function(){this.Db&&
a._free(this.Db);this.delete()};a.fc=a.fc||function(){}})})(p);
(function(a){function e(c,b,d,g,k){for(var n=0;n<c.length;n++)b[n*d+(n*k+g+d)%d]=c[n];return b}function f(c){for(var b=c*c,d=Array(b);b--;)d[b]=0===b%(c+1)?1:0;return d}function h(c){return(w(255*c[3])<<24|w(255*c[0])<<16|w(255*c[1])<<8|w(255*c[2])<<0)>>>0}function l(c){if(c&&c._ck)return c;if(c instanceof Float32Array){for(var b=Math.floor(c.length/4),d=new Uint32Array(b),g=0;g<b;g++)d[g]=h(c.slice(4*g,4*(g+1)));return d}if(c instanceof Uint32Array)return c;if(c instanceof Array&&c[0]instanceof Float32Array)return c.map(h)}
function q(c){if(void 0===c)return 1;var b=parseFloat(c);return c&&-1!==c.indexOf("%")?b/100:b}function w(c){return Math.round(Math.max(0,Math.min(c||0,255)))}function t(c,b){b&&b._ck||a._free(c)}function r(c,b,d){if(!c||!c.length)return I;if(c&&c._ck)return c.byteOffset;var g=a[b].BYTES_PER_ELEMENT;d||(d=a._malloc(c.length*g));a[b].set(c,d/g);return d}function y(c){var b={hb:I,count:c.length,colorType:a.ColorType.RGBA_F32};if(c instanceof Float32Array)b.hb=r(c,"HEAPF32"),b.count=c.length/4;else if(c instanceof
Uint32Array)b.hb=r(c,"HEAPU32"),b.colorType=a.ColorType.RGBA_8888;else if(c instanceof Array){if(c&&c.length){for(var d=a._malloc(16*c.length),g=0,k=d/4,n=0;n<c.length;n++)for(var v=0;4>v;v++)a.HEAPF32[k+g]=c[n][v],g++;c=d}else c=I;b.hb=c}else throw"Invalid argument to copyFlexibleColorArray, Not a color array "+typeof c;return b}function A(c){if(!c)return I;var b=rb.toTypedArray();if(c.length){if(6===c.length||9===c.length)return r(c,"HEAPF32",ja),6===c.length&&a.HEAPF32.set(Pc,6+ja/4),ja;if(16===
c.length)return b[0]=c[0],b[1]=c[1],b[2]=c[3],b[3]=c[4],b[4]=c[5],b[5]=c[7],b[6]=c[12],b[7]=c[13],b[8]=c[15],ja;throw"invalid matrix size";}if(void 0===c.m11)throw"invalid matrix argument";b[0]=c.m11;b[1]=c.m21;b[2]=c.m41;b[3]=c.m12;b[4]=c.m22;b[5]=c.m42;b[6]=c.m14;b[7]=c.m24;b[8]=c.m44;return ja}function B(c){if(!c)return I;var b=sb.toTypedArray();if(c.length){if(16!==c.length&&6!==c.length&&9!==c.length)throw"invalid matrix size";if(16===c.length)return r(c,"HEAPF32",Ba);b.fill(0);b[0]=c[0];b[1]=
c[1];b[3]=c[2];b[4]=c[3];b[5]=c[4];b[7]=c[5];b[10]=1;b[12]=c[6];b[13]=c[7];b[15]=c[8];6===c.length&&(b[12]=0,b[13]=0,b[15]=1);return Ba}if(void 0===c.m11)throw"invalid matrix argument";b[0]=c.m11;b[1]=c.m21;b[2]=c.m31;b[3]=c.m41;b[4]=c.m12;b[5]=c.m22;b[6]=c.m32;b[7]=c.m42;b[8]=c.m13;b[9]=c.m23;b[10]=c.m33;b[11]=c.m43;b[12]=c.m14;b[13]=c.m24;b[14]=c.m34;b[15]=c.m44;return Ba}function F(c,b){return r(c,"HEAPF32",b||va)}function u(c,b,d,g){var k=tb.toTypedArray();k[0]=c;k[1]=b;k[2]=d;k[3]=g;return va}
function C(c){for(var b=new Float32Array(4),d=0;4>d;d++)b[d]=a.HEAPF32[c/4+d];return b}function E(c,b){return r(c,"HEAPF32",b||M)}function N(c,b){return r(c,"HEAPF32",b||ub)}function ka(){for(var c=0,b=0;b<arguments.length-1;b+=2)c+=arguments[b]*arguments[b+1];return c}function ba(c,b,d){for(var g=Array(c.length),k=0;k<d;k++)for(var n=0;n<d;n++){for(var v=0,z=0;z<d;z++)v+=c[d*k+z]*b[d*z+n];g[k*d+n]=v}return g}function Ma(c,b){for(var d=ba(b[0],b[1],c),g=2;g<b.length;)d=ba(d,b[g],c),g++;return d}a.Color=
function(c,b,d,g){void 0===g&&(g=1);return a.Color4f(w(c)/255,w(b)/255,w(d)/255,g)};a.ColorAsInt=function(c,b,d,g){void 0===g&&(g=255);return(w(g)<<24|w(c)<<16|w(b)<<8|w(d)<<0&268435455)>>>0};a.Color4f=function(c,b,d,g){void 0===g&&(g=1);return Float32Array.of(c,b,d,g)};Object.defineProperty(a,"TRANSPARENT",{get:function(){return a.Color4f(0,0,0,0)}});Object.defineProperty(a,"BLACK",{get:function(){return a.Color4f(0,0,0,1)}});Object.defineProperty(a,"WHITE",{get:function(){return a.Color4f(1,1,1,
1)}});Object.defineProperty(a,"RED",{get:function(){return a.Color4f(1,0,0,1)}});Object.defineProperty(a,"GREEN",{get:function(){return a.Color4f(0,1,0,1)}});Object.defineProperty(a,"BLUE",{get:function(){return a.Color4f(0,0,1,1)}});Object.defineProperty(a,"YELLOW",{get:function(){return a.Color4f(1,1,0,1)}});Object.defineProperty(a,"CYAN",{get:function(){return a.Color4f(0,1,1,1)}});Object.defineProperty(a,"MAGENTA",{get:function(){return a.Color4f(1,0,1,1)}});a.getColorComponents=function(c){return[Math.floor(255*
c[0]),Math.floor(255*c[1]),Math.floor(255*c[2]),c[3]]};a.parseColorString=function(c,b){c=c.toLowerCase();if(c.startsWith("#")){b=255;switch(c.length){case 9:b=parseInt(c.slice(7,9),16);case 7:var d=parseInt(c.slice(1,3),16);var g=parseInt(c.slice(3,5),16);var k=parseInt(c.slice(5,7),16);break;case 5:b=17*parseInt(c.slice(4,5),16);case 4:d=17*parseInt(c.slice(1,2),16),g=17*parseInt(c.slice(2,3),16),k=17*parseInt(c.slice(3,4),16)}return a.Color(d,g,k,b/255)}return c.startsWith("rgba")?(c=c.slice(5,
-1),c=c.split(","),a.Color(+c[0],+c[1],+c[2],q(c[3]))):c.startsWith("rgb")?(c=c.slice(4,-1),c=c.split(","),a.Color(+c[0],+c[1],+c[2],q(c[3]))):c.startsWith("gray(")||c.startsWith("hsl")||!b||(c=b[c],void 0===c)?a.BLACK:c};a.multiplyByAlpha=function(c,b){c=c.slice();c[3]=Math.max(0,Math.min(c[3]*b,1));return c};a.Malloc=function(c,b){var d=a._malloc(b*c.BYTES_PER_ELEMENT);return{_ck:!0,length:b,byteOffset:d,qb:null,subarray:function(g,k){g=this.toTypedArray().subarray(g,k);g._ck=!0;return g},toTypedArray:function(){if(this.qb&&
this.qb.length)return this.qb;this.qb=new c(a.HEAPU8.buffer,d,b);this.qb._ck=!0;return this.qb}}};a.Free=function(c){a._free(c.byteOffset);c.byteOffset=I;c.toTypedArray=null;c.qb=null};var ja=I,rb,Ba=I,sb,va=I,tb,Y,M=I,$b,ta=I,ac,vb=I,bc,wb=I,xb,$a=I,cc,ub=I,dc,ec=I,Pc=Float32Array.of(0,0,1),I=0;a.onRuntimeInitialized=function(){function c(b,d,g,k,n,v){v||(v=4*k.width,k.colorType===a.ColorType.RGBA_F16?v*=2:k.colorType===a.ColorType.RGBA_F32&&(v*=4));var z=v*k.height;var D=n?n.byteOffset:a._malloc(z);
if(!b._readPixels(k,D,v,d,g))return n||a._free(D),null;if(n)return n.toTypedArray();switch(k.colorType){case a.ColorType.RGBA_8888:case a.ColorType.RGBA_F16:b=(new Uint8Array(a.HEAPU8.buffer,D,z)).slice();break;case a.ColorType.RGBA_F32:b=(new Float32Array(a.HEAPU8.buffer,D,z)).slice();break;default:return null}a._free(D);return b}tb=a.Malloc(Float32Array,4);va=tb.byteOffset;sb=a.Malloc(Float32Array,16);Ba=sb.byteOffset;rb=a.Malloc(Float32Array,9);ja=rb.byteOffset;cc=a.Malloc(Float32Array,12);ub=
cc.byteOffset;dc=a.Malloc(Float32Array,12);ec=dc.byteOffset;Y=a.Malloc(Float32Array,4);M=Y.byteOffset;$b=a.Malloc(Float32Array,4);ta=$b.byteOffset;ac=a.Malloc(Float32Array,3);vb=ac.byteOffset;bc=a.Malloc(Float32Array,3);wb=bc.byteOffset;xb=a.Malloc(Int32Array,4);$a=xb.byteOffset;a.ColorSpace.SRGB=a.ColorSpace._MakeSRGB();a.ColorSpace.DISPLAY_P3=a.ColorSpace._MakeDisplayP3();a.ColorSpace.ADOBE_RGB=a.ColorSpace._MakeAdobeRGB();a.GlyphRunFlags={IsWhiteSpace:a._GlyphRunFlags_isWhiteSpace};a.Path.MakeFromCmds=
function(b){var d=r(b,"HEAPF32"),g=a.Path._MakeFromCmds(d,b.length);t(d,b);return g};a.Path.MakeFromVerbsPointsWeights=function(b,d,g){var k=r(b,"HEAPU8"),n=r(d,"HEAPF32"),v=r(g,"HEAPF32"),z=a.Path._MakeFromVerbsPointsWeights(k,b.length,n,d.length,v,g&&g.length||0);t(k,b);t(n,d);t(v,g);return z};a.Path.prototype.addArc=function(b,d,g){b=E(b);this._addArc(b,d,g);return this};a.Path.prototype.addCircle=function(b,d,g,k){this._addCircle(b,d,g,!!k);return this};a.Path.prototype.addOval=function(b,d,g){void 0===
g&&(g=1);b=E(b);this._addOval(b,!!d,g);return this};a.Path.prototype.addPath=function(){var b=Array.prototype.slice.call(arguments),d=b[0],g=!1;"boolean"===typeof b[b.length-1]&&(g=b.pop());if(1===b.length)this._addPath(d,1,0,0,0,1,0,0,0,1,g);else if(2===b.length)b=b[1],this._addPath(d,b[0],b[1],b[2],b[3],b[4],b[5],b[6]||0,b[7]||0,b[8]||1,g);else if(7===b.length||10===b.length)this._addPath(d,b[1],b[2],b[3],b[4],b[5],b[6],b[7]||0,b[8]||0,b[9]||1,g);else return null;return this};a.Path.prototype.addPoly=
function(b,d){var g=r(b,"HEAPF32");this._addPoly(g,b.length/2,d);t(g,b);return this};a.Path.prototype.addRect=function(b,d){b=E(b);this._addRect(b,!!d);return this};a.Path.prototype.addRRect=function(b,d){b=N(b);this._addRRect(b,!!d);return this};a.Path.prototype.addVerbsPointsWeights=function(b,d,g){var k=r(b,"HEAPU8"),n=r(d,"HEAPF32"),v=r(g,"HEAPF32");this._addVerbsPointsWeights(k,b.length,n,d.length,v,g&&g.length||0);t(k,b);t(n,d);t(v,g)};a.Path.prototype.arc=function(b,d,g,k,n,v){b=a.LTRBRect(b-
g,d-g,b+g,d+g);n=(n-k)/Math.PI*180-360*!!v;v=new a.Path;v.addArc(b,k/Math.PI*180,n);this.addPath(v,!0);v.delete();return this};a.Path.prototype.arcToOval=function(b,d,g,k){b=E(b);this._arcToOval(b,d,g,k);return this};a.Path.prototype.arcToRotated=function(b,d,g,k,n,v,z){this._arcToRotated(b,d,g,!!k,!!n,v,z);return this};a.Path.prototype.arcToTangent=function(b,d,g,k,n){this._arcToTangent(b,d,g,k,n);return this};a.Path.prototype.close=function(){this._close();return this};a.Path.prototype.conicTo=
function(b,d,g,k,n){this._conicTo(b,d,g,k,n);return this};a.Path.prototype.computeTightBounds=function(b){this._computeTightBounds(M);var d=Y.toTypedArray();return b?(b.set(d),b):d.slice()};a.Path.prototype.cubicTo=function(b,d,g,k,n,v){this._cubicTo(b,d,g,k,n,v);return this};a.Path.prototype.dash=function(b,d,g){return this._dash(b,d,g)?this:null};a.Path.prototype.getBounds=function(b){this._getBounds(M);var d=Y.toTypedArray();return b?(b.set(d),b):d.slice()};a.Path.prototype.lineTo=function(b,d){this._lineTo(b,
d);return this};a.Path.prototype.moveTo=function(b,d){this._moveTo(b,d);return this};a.Path.prototype.offset=function(b,d){this._transform(1,0,b,0,1,d,0,0,1);return this};a.Path.prototype.quadTo=function(b,d,g,k){this._quadTo(b,d,g,k);return this};a.Path.prototype.rArcTo=function(b,d,g,k,n,v,z){this._rArcTo(b,d,g,k,n,v,z);return this};a.Path.prototype.rConicTo=function(b,d,g,k,n){this._rConicTo(b,d,g,k,n);return this};a.Path.prototype.rCubicTo=function(b,d,g,k,n,v){this._rCubicTo(b,d,g,k,n,v);return this};
a.Path.prototype.rLineTo=function(b,d){this._rLineTo(b,d);return this};a.Path.prototype.rMoveTo=function(b,d){this._rMoveTo(b,d);return this};a.Path.prototype.rQuadTo=function(b,d,g,k){this._rQuadTo(b,d,g,k);return this};a.Path.prototype.stroke=function(b){b=b||{};b.width=b.width||1;b.miter_limit=b.miter_limit||4;b.cap=b.cap||a.StrokeCap.Butt;b.join=b.join||a.StrokeJoin.Miter;b.precision=b.precision||1;return this._stroke(b)?this:null};a.Path.prototype.transform=function(){if(1===arguments.length){var b=
arguments[0];this._transform(b[0],b[1],b[2],b[3],b[4],b[5],b[6]||0,b[7]||0,b[8]||1)}else if(6===arguments.length||9===arguments.length)b=arguments,this._transform(b[0],b[1],b[2],b[3],b[4],b[5],b[6]||0,b[7]||0,b[8]||1);else throw"transform expected to take 1 or 9 arguments. Got "+arguments.length;return this};a.Path.prototype.trim=function(b,d,g){return this._trim(b,d,!!g)?this:null};a.Image.prototype.makeShaderCubic=function(b,d,g,k,n){n=A(n);return this._makeShaderCubic(b,d,g,k,n)};a.Image.prototype.makeShaderOptions=
function(b,d,g,k,n){n=A(n);return this._makeShaderOptions(b,d,g,k,n)};a.Image.prototype.readPixels=function(b,d,g,k,n){return c(this,b,d,g,k,n)};a.Canvas.prototype.clear=function(b){b=F(b);this._clear(b)};a.Canvas.prototype.clipRRect=function(b,d,g){b=N(b);this._clipRRect(b,d,g)};a.Canvas.prototype.clipRect=function(b,d,g){b=E(b);this._clipRect(b,d,g)};a.Canvas.prototype.concat=function(b){b=B(b);this._concat(b)};a.Canvas.prototype.drawArc=function(b,d,g,k,n){b=E(b);this._drawArc(b,d,g,k,n)};a.Canvas.prototype.drawAtlas=
function(b,d,g,k,n,v,z){if(b&&k&&d&&g&&d.length===g.length){n||(n=a.BlendMode.SrcOver);var D=r(d,"HEAPF32"),G=r(g,"HEAPF32"),J=g.length/4,m=r(l(v),"HEAPU32");if(z&&"B"in z&&"C"in z)this._drawAtlasCubic(b,G,D,m,J,n,z.B,z.C,k);else{let x=a.FilterMode.Linear,H=a.MipmapMode.None;z&&(x=z.filter,"mipmap"in z&&(H=z.mipmap));this._drawAtlasOptions(b,G,D,m,J,n,x,H,k)}t(D,d);t(G,g);t(m,v)}};a.Canvas.prototype.drawCircle=function(b,d,g,k){this._drawCircle(b,d,g,k)};a.Canvas.prototype.drawColor=function(b,d){b=
F(b);void 0!==d?this._drawColor(b,d):this._drawColor(b)};a.Canvas.prototype.drawColorInt=function(b,d){this._drawColorInt(b,d||a.BlendMode.SrcOver)};a.Canvas.prototype.drawColorComponents=function(b,d,g,k,n){b=u(b,d,g,k);void 0!==n?this._drawColor(b,n):this._drawColor(b)};a.Canvas.prototype.drawDRRect=function(b,d,g){b=N(b,ub);d=N(d,ec);this._drawDRRect(b,d,g)};a.Canvas.prototype.drawImage=function(b,d,g,k){this._drawImage(b,d,g,k||null)};a.Canvas.prototype.drawImageCubic=function(b,d,g,k,n,v){this._drawImageCubic(b,
d,g,k,n,v||null)};a.Canvas.prototype.drawImageOptions=function(b,d,g,k,n,v){this._drawImageOptions(b,d,g,k,n,v||null)};a.Canvas.prototype.drawImageNine=function(b,d,g,k,n){d=r(d,"HEAP32",$a);g=E(g);this._drawImageNine(b,d,g,k,n||null)};a.Canvas.prototype.drawImageRect=function(b,d,g,k,n){E(d,M);E(g,ta);this._drawImageRect(b,M,ta,k,!!n)};a.Canvas.prototype.drawImageRectCubic=function(b,d,g,k,n,v){E(d,M);E(g,ta);this._drawImageRectCubic(b,M,ta,k,n,v||null)};a.Canvas.prototype.drawImageRectOptions=function(b,
d,g,k,n,v){E(d,M);E(g,ta);this._drawImageRectOptions(b,M,ta,k,n,v||null)};a.Canvas.prototype.drawLine=function(b,d,g,k,n){this._drawLine(b,d,g,k,n)};a.Canvas.prototype.drawOval=function(b,d){b=E(b);this._drawOval(b,d)};a.Canvas.prototype.drawPaint=function(b){this._drawPaint(b)};a.Canvas.prototype.drawParagraph=function(b,d,g){this._drawParagraph(b,d,g)};a.Canvas.prototype.drawPatch=function(b,d,g,k,n){if(24>b.length)throw"Need 12 cubic points";if(d&&4>d.length)throw"Need 4 colors";if(g&&8>g.length)throw"Need 4 shader coordinates";
const v=r(b,"HEAPF32"),z=d?r(l(d),"HEAPU32"):I,D=g?r(g,"HEAPF32"):I;k||(k=a.BlendMode.Modulate);this._drawPatch(v,z,D,k,n);t(D,g);t(z,d);t(v,b)};a.Canvas.prototype.drawPath=function(b,d){this._drawPath(b,d)};a.Canvas.prototype.drawPicture=function(b){this._drawPicture(b)};a.Canvas.prototype.drawPoints=function(b,d,g){var k=r(d,"HEAPF32");this._drawPoints(b,k,d.length/2,g);t(k,d)};a.Canvas.prototype.drawRRect=function(b,d){b=N(b);this._drawRRect(b,d)};a.Canvas.prototype.drawRect=function(b,d){b=E(b);
this._drawRect(b,d)};a.Canvas.prototype.drawRect4f=function(b,d,g,k,n){this._drawRect4f(b,d,g,k,n)};a.Canvas.prototype.drawShadow=function(b,d,g,k,n,v,z){var D=r(n,"HEAPF32"),G=r(v,"HEAPF32");d=r(d,"HEAPF32",vb);g=r(g,"HEAPF32",wb);this._drawShadow(b,d,g,k,D,G,z);t(D,n);t(G,v)};a.getShadowLocalBounds=function(b,d,g,k,n,v,z){b=A(b);g=r(g,"HEAPF32",vb);k=r(k,"HEAPF32",wb);if(!this._getShadowLocalBounds(b,d,g,k,n,v,M))return null;d=Y.toTypedArray();return z?(z.set(d),z):d.slice()};a.Canvas.prototype.drawTextBlob=
function(b,d,g,k){this._drawTextBlob(b,d,g,k)};a.Canvas.prototype.drawVertices=function(b,d,g){this._drawVertices(b,d,g)};a.Canvas.prototype.getDeviceClipBounds=function(b){this._getDeviceClipBounds($a);var d=xb.toTypedArray();b?b.set(d):b=d.slice();return b};a.Canvas.prototype.getLocalToDevice=function(){this._getLocalToDevice(Ba);for(var b=Ba,d=Array(16),g=0;16>g;g++)d[g]=a.HEAPF32[b/4+g];return d};a.Canvas.prototype.getTotalMatrix=function(){this._getTotalMatrix(ja);for(var b=Array(9),d=0;9>d;d++)b[d]=
a.HEAPF32[ja/4+d];return b};a.Canvas.prototype.makeSurface=function(b){b=this._makeSurface(b);b.vb=this.vb;return b};a.Canvas.prototype.readPixels=function(b,d,g,k,n){return c(this,b,d,g,k,n)};a.Canvas.prototype.saveLayer=function(b,d,g,k){d=E(d);return this._saveLayer(b||null,d,g||null,k||0)};a.Canvas.prototype.writePixels=function(b,d,g,k,n,v,z,D){if(b.byteLength%(d*g))throw"pixels length must be a multiple of the srcWidth * srcHeight";var G=b.byteLength/(d*g);v=v||a.AlphaType.Unpremul;z=z||a.ColorType.RGBA_8888;
D=D||a.ColorSpace.SRGB;var J=G*d;G=r(b,"HEAPU8");d=this._writePixels({width:d,height:g,colorType:z,alphaType:v,colorSpace:D},G,J,k,n);t(G,b);return d};a.ColorFilter.MakeBlend=function(b,d){b=F(b);return a.ColorFilter._MakeBlend(b,d)};a.ColorFilter.MakeMatrix=function(b){if(!b||20!==b.length)throw"invalid color matrix";var d=r(b,"HEAPF32"),g=a.ColorFilter._makeMatrix(d);t(d,b);return g};a.ContourMeasure.prototype.getPosTan=function(b,d){this._getPosTan(b,M);b=Y.toTypedArray();return d?(d.set(b),d):
b.slice()};a.ImageFilter.MakeDropShadow=function(b,d,g,k,n,v){n=F(n,va);return a.ImageFilter._MakeDropShadow(b,d,g,k,n,v)};a.ImageFilter.MakeDropShadowOnly=function(b,d,g,k,n,v){n=F(n,va);return a.ImageFilter._MakeDropShadowOnly(b,d,g,k,n,v)};a.ImageFilter.MakeImage=function(b,d,g,k){g=E(g,M);k=E(k,ta);if("B"in d&&"C"in d)return a.ImageFilter._MakeImageCubic(b,d.Lb,d.Mb,g,k);const n=d.filter;let v=a.MipmapMode.None;"mipmap"in d&&(v=d.mipmap);return a.ImageFilter._MakeImageOptions(b,n,v,g,k)};a.ImageFilter.MakeMatrixTransform=
function(b,d,g){b=A(b);if("B"in d&&"C"in d)return a.ImageFilter._MakeMatrixTransformCubic(b,d.Lb,d.Mb,g);const k=d.filter;let n=a.MipmapMode.None;"mipmap"in d&&(n=d.mipmap);return a.ImageFilter._MakeMatrixTransformOptions(b,k,n,g)};a.Paint.prototype.getColor=function(){this._getColor(va);return C(va)};a.Paint.prototype.setColor=function(b,d){d=d||null;b=F(b);this._setColor(b,d)};a.Paint.prototype.setColorComponents=function(b,d,g,k,n){n=n||null;b=u(b,d,g,k);this._setColor(b,n)};a.Path.prototype.getPoint=
function(b,d){this._getPoint(b,M);b=Y.toTypedArray();return d?(d[0]=b[0],d[1]=b[1],d):b.slice(0,2)};a.Picture.prototype.makeShader=function(b,d,g,k,n){k=A(k);n=E(n);return this._makeShader(b,d,g,k,n)};a.PictureRecorder.prototype.beginRecording=function(b){b=E(b);return this._beginRecording(b)};a.Surface.prototype.getCanvas=function(){var b=this._getCanvas();b.vb=this.vb;return b};a.Surface.prototype.makeImageSnapshot=function(b){b=r(b,"HEAP32",$a);return this._makeImageSnapshot(b)};a.Surface.prototype.makeSurface=
function(b){b=this._makeSurface(b);b.vb=this.vb;return b};a.Surface.prototype.Qb=function(b,d){this.ub||(this.ub=this.getCanvas());requestAnimationFrame(function(){b(this.ub);this.flush(d)}.bind(this))};a.Surface.prototype.requestAnimationFrame||(a.Surface.prototype.requestAnimationFrame=a.Surface.prototype.Qb);a.Surface.prototype.Nb=function(b,d){this.ub||(this.ub=this.getCanvas());requestAnimationFrame(function(){b(this.ub);this.flush(d);this.dispose()}.bind(this))};a.Surface.prototype.drawOnce||
(a.Surface.prototype.drawOnce=a.Surface.prototype.Nb);a.PathEffect.MakeDash=function(b,d){d||(d=0);if(!b.length||1===b.length%2)throw"Intervals array must have even length";var g=r(b,"HEAPF32");d=a.PathEffect._MakeDash(g,b.length,d);t(g,b);return d};a.PathEffect.MakeLine2D=function(b,d){d=A(d);return a.PathEffect._MakeLine2D(b,d)};a.PathEffect.MakePath2D=function(b,d){b=A(b);return a.PathEffect._MakePath2D(b,d)};a.Shader.MakeColor=function(b,d){d=d||null;b=F(b);return a.Shader._MakeColor(b,d)};a.Shader.Blend=
a.Shader.MakeBlend;a.Shader.Color=a.Shader.MakeColor;a.Shader.MakeLinearGradient=function(b,d,g,k,n,v,z,D){D=D||null;var G=y(g),J=r(k,"HEAPF32");z=z||0;v=A(v);var m=Y.toTypedArray();m.set(b);m.set(d,2);b=a.Shader._MakeLinearGradient(M,G.hb,G.colorType,J,G.count,n,z,v,D);t(G.hb,g);k&&t(J,k);return b};a.Shader.MakeRadialGradient=function(b,d,g,k,n,v,z,D){D=D||null;var G=y(g),J=r(k,"HEAPF32");z=z||0;v=A(v);b=a.Shader._MakeRadialGradient(b[0],b[1],d,G.hb,G.colorType,J,G.count,n,z,v,D);t(G.hb,g);k&&t(J,
k);return b};a.Shader.MakeSweepGradient=function(b,d,g,k,n,v,z,D,G,J){J=J||null;var m=y(g),x=r(k,"HEAPF32");z=z||0;D=D||0;G=G||360;v=A(v);b=a.Shader._MakeSweepGradient(b,d,m.hb,m.colorType,x,m.count,n,D,G,z,v,J);t(m.hb,g);k&&t(x,k);return b};a.Shader.MakeTwoPointConicalGradient=function(b,d,g,k,n,v,z,D,G,J){J=J||null;var m=y(n),x=r(v,"HEAPF32");G=G||0;D=A(D);var H=Y.toTypedArray();H.set(b);H.set(g,2);b=a.Shader._MakeTwoPointConicalGradient(M,d,k,m.hb,m.colorType,x,m.count,z,G,D,J);t(m.hb,n);v&&t(x,
v);return b};a.Vertices.prototype.bounds=function(b){this._bounds(M);var d=Y.toTypedArray();return b?(b.set(d),b):d.slice()};a.bb&&a.bb.forEach(function(b){b()})};a.computeTonalColors=function(c){var b=r(c.ambient,"HEAPF32"),d=r(c.spot,"HEAPF32");this._computeTonalColors(b,d);var g={ambient:C(b),spot:C(d)};t(b,c.ambient);t(d,c.spot);return g};a.LTRBRect=function(c,b,d,g){return Float32Array.of(c,b,d,g)};a.XYWHRect=function(c,b,d,g){return Float32Array.of(c,b,c+d,b+g)};a.LTRBiRect=function(c,b,d,g){return Int32Array.of(c,
b,d,g)};a.XYWHiRect=function(c,b,d,g){return Int32Array.of(c,b,c+d,b+g)};a.RRectXY=function(c,b,d){return Float32Array.of(c[0],c[1],c[2],c[3],b,d,b,d,b,d,b,d)};a.MakeAnimatedImageFromEncoded=function(c){c=new Uint8Array(c);var b=a._malloc(c.byteLength);a.HEAPU8.set(c,b);return(c=a._decodeAnimatedImage(b,c.byteLength))?c:null};a.MakeImageFromEncoded=function(c){c=new Uint8Array(c);var b=a._malloc(c.byteLength);a.HEAPU8.set(c,b);return(c=a._decodeImage(b,c.byteLength))?c:null};var Na=null;a.MakeImageFromCanvasImageSource=
function(c){var b=c.width,d=c.height;Na||(Na=document.createElement("canvas"));Na.width=b;Na.height=d;var g=Na.getContext("2d",{sc:!0});g.drawImage(c,0,0);c=g.getImageData(0,0,b,d);return a.MakeImage({width:b,height:d,alphaType:a.AlphaType.Unpremul,colorType:a.ColorType.RGBA_8888,colorSpace:a.ColorSpace.SRGB},c.data,4*b)};a.MakeImage=function(c,b,d){var g=a._malloc(b.length);a.HEAPU8.set(b,g);return a._MakeImage(c,g,b.length,d)};a.MakeVertices=function(c,b,d,g,k,n){var v=k&&k.length||0,z=0;d&&d.length&&
(z|=1);g&&g.length&&(z|=2);void 0===n||n||(z|=4);c=new a._VerticesBuilder(c,b.length/2,v,z);r(b,"HEAPF32",c.positions());c.texCoords()&&r(d,"HEAPF32",c.texCoords());c.colors()&&r(l(g),"HEAPU32",c.colors());c.indices()&&r(k,"HEAPU16",c.indices());return c.detach()};a.Matrix={};a.Matrix.identity=function(){return f(3)};a.Matrix.invert=function(c){var b=c[0]*c[4]*c[8]+c[1]*c[5]*c[6]+c[2]*c[3]*c[7]-c[2]*c[4]*c[6]-c[1]*c[3]*c[8]-c[0]*c[5]*c[7];return b?[(c[4]*c[8]-c[5]*c[7])/b,(c[2]*c[7]-c[1]*c[8])/b,
(c[1]*c[5]-c[2]*c[4])/b,(c[5]*c[6]-c[3]*c[8])/b,(c[0]*c[8]-c[2]*c[6])/b,(c[2]*c[3]-c[0]*c[5])/b,(c[3]*c[7]-c[4]*c[6])/b,(c[1]*c[6]-c[0]*c[7])/b,(c[0]*c[4]-c[1]*c[3])/b]:null};a.Matrix.mapPoints=function(c,b){for(var d=0;d<b.length;d+=2){var g=b[d],k=b[d+1],n=c[6]*g+c[7]*k+c[8],v=c[3]*g+c[4]*k+c[5];b[d]=(c[0]*g+c[1]*k+c[2])/n;b[d+1]=v/n}return b};a.Matrix.multiply=function(){return Ma(3,arguments)};a.Matrix.rotated=function(c,b,d){b=b||0;d=d||0;var g=Math.sin(c);c=Math.cos(c);return[c,-g,ka(g,d,1-
c,b),g,c,ka(-g,b,1-c,d),0,0,1]};a.Matrix.scaled=function(c,b,d,g){d=d||0;g=g||0;var k=e([c,b],f(3),3,0,1);return e([d-c*d,g-b*g],k,3,2,0)};a.Matrix.skewed=function(c,b,d,g){d=d||0;g=g||0;var k=e([c,b],f(3),3,1,-1);return e([-c*d,-b*g],k,3,2,0)};a.Matrix.translated=function(c,b){return e(arguments,f(3),3,2,0)};a.Vector={};a.Vector.dot=function(c,b){return c.map(function(d,g){return d*b[g]}).reduce(function(d,g){return d+g})};a.Vector.lengthSquared=function(c){return a.Vector.dot(c,c)};a.Vector.length=
function(c){return Math.sqrt(a.Vector.lengthSquared(c))};a.Vector.mulScalar=function(c,b){return c.map(function(d){return d*b})};a.Vector.add=function(c,b){return c.map(function(d,g){return d+b[g]})};a.Vector.sub=function(c,b){return c.map(function(d,g){return d-b[g]})};a.Vector.dist=function(c,b){return a.Vector.length(a.Vector.sub(c,b))};a.Vector.normalize=function(c){return a.Vector.mulScalar(c,1/a.Vector.length(c))};a.Vector.cross=function(c,b){return[c[1]*b[2]-c[2]*b[1],c[2]*b[0]-c[0]*b[2],c[0]*
b[1]-c[1]*b[0]]};a.M44={};a.M44.identity=function(){return f(4)};a.M44.translated=function(c){return e(c,f(4),4,3,0)};a.M44.scaled=function(c){return e(c,f(4),4,0,1)};a.M44.rotated=function(c,b){return a.M44.rotatedUnitSinCos(a.Vector.normalize(c),Math.sin(b),Math.cos(b))};a.M44.rotatedUnitSinCos=function(c,b,d){var g=c[0],k=c[1];c=c[2];var n=1-d;return[n*g*g+d,n*g*k-b*c,n*g*c+b*k,0,n*g*k+b*c,n*k*k+d,n*k*c-b*g,0,n*g*c-b*k,n*k*c+b*g,n*c*c+d,0,0,0,0,1]};a.M44.lookat=function(c,b,d){b=a.Vector.normalize(a.Vector.sub(b,
c));d=a.Vector.normalize(d);d=a.Vector.normalize(a.Vector.cross(b,d));var g=a.M44.identity();e(d,g,4,0,0);e(a.Vector.cross(d,b),g,4,1,0);e(a.Vector.mulScalar(b,-1),g,4,2,0);e(c,g,4,3,0);c=a.M44.invert(g);return null===c?a.M44.identity():c};a.M44.perspective=function(c,b,d){var g=1/(b-c);d/=2;d=Math.cos(d)/Math.sin(d);return[d,0,0,0,0,d,0,0,0,0,(b+c)*g,2*b*c*g,0,0,-1,1]};a.M44.rc=function(c,b,d){return c[4*b+d]};a.M44.multiply=function(){return Ma(4,arguments)};a.M44.invert=function(c){var b=c[0],
d=c[4],g=c[8],k=c[12],n=c[1],v=c[5],z=c[9],D=c[13],G=c[2],J=c[6],m=c[10],x=c[14],H=c[3],L=c[7],Z=c[11];c=c[15];var ma=b*v-d*n,na=b*z-g*n,ra=b*D-k*n,S=d*z-g*v,Ca=d*D-k*v,Da=g*D-k*z,Ea=G*L-J*H,Fa=G*Z-m*H,Ga=G*c-x*H,Ha=J*Z-m*L,Ia=J*c-x*L,Ja=m*c-x*Z,fc=ma*Ja-na*Ia+ra*Ha+S*Ga-Ca*Fa+Da*Ea,aa=1/fc;if(0===fc||Infinity===aa)return null;ma*=aa;na*=aa;ra*=aa;S*=aa;Ca*=aa;Da*=aa;Ea*=aa;Fa*=aa;Ga*=aa;Ha*=aa;Ia*=aa;Ja*=aa;b=[v*Ja-z*Ia+D*Ha,z*Ga-n*Ja-D*Fa,n*Ia-v*Ga+D*Ea,v*Fa-n*Ha-z*Ea,g*Ia-d*Ja-k*Ha,b*Ja-g*Ga+k*
Fa,d*Ga-b*Ia-k*Ea,b*Ha-d*Fa+g*Ea,L*Da-Z*Ca+c*S,Z*ra-H*Da-c*na,H*Ca-L*ra+c*ma,L*na-H*S-Z*ma,m*Ca-J*Da-x*S,G*Da-m*ra+x*na,J*ra-G*Ca-x*ma,G*S-J*na+m*ma];return b.every(function(yb){return!isNaN(yb)&&Infinity!==yb&&-Infinity!==yb})?b:null};a.M44.transpose=function(c){return[c[0],c[4],c[8],c[12],c[1],c[5],c[9],c[13],c[2],c[6],c[10],c[14],c[3],c[7],c[11],c[15]]};a.M44.mustInvert=function(c){c=a.M44.invert(c);if(null===c)throw"Matrix not invertible";return c};a.M44.setupCamera=function(c,b,d){var g=a.M44.lookat(d.eye,
d.coa,d.up);d=a.M44.perspective(d.near,d.far,d.angle);b=[(c[2]-c[0])/2,(c[3]-c[1])/2,b];c=a.M44.multiply(a.M44.translated([(c[0]+c[2])/2,(c[1]+c[3])/2,0]),a.M44.scaled(b));return a.M44.multiply(c,d,g,a.M44.mustInvert(c))};a.ColorMatrix={};a.ColorMatrix.identity=function(){var c=new Float32Array(20);c[0]=1;c[6]=1;c[12]=1;c[18]=1;return c};a.ColorMatrix.scaled=function(c,b,d,g){var k=new Float32Array(20);k[0]=c;k[6]=b;k[12]=d;k[18]=g;return k};var Qc=[[6,7,11,12],[0,10,2,12],[0,1,5,6]];a.ColorMatrix.rotated=
function(c,b,d){var g=a.ColorMatrix.identity();c=Qc[c];g[c[0]]=d;g[c[1]]=b;g[c[2]]=-b;g[c[3]]=d;return g};a.ColorMatrix.postTranslate=function(c,b,d,g,k){c[4]+=b;c[9]+=d;c[14]+=g;c[19]+=k;return c};a.ColorMatrix.concat=function(c,b){for(var d=new Float32Array(20),g=0,k=0;20>k;k+=5){for(var n=0;4>n;n++)d[g++]=c[k]*b[n]+c[k+1]*b[n+5]+c[k+2]*b[n+10]+c[k+3]*b[n+15];d[g++]=c[k]*b[4]+c[k+1]*b[9]+c[k+2]*b[14]+c[k+3]*b[19]+c[k+4]}return d};(function(c){c.bb=c.bb||[];c.bb.push(function(){function b(m){if(!m||
!m.length)return[];for(var x=[],H=0;H<m.length;H+=5){var L=c.LTRBRect(m[H],m[H+1],m[H+2],m[H+3]);L.direction=0===m[H+4]?c.TextDirection.RTL:c.TextDirection.LTR;x.push(L)}c._free(m.byteOffset);return x}function d(m){m=m||{};void 0===m.weight&&(m.weight=c.FontWeight.Normal);m.width=m.width||c.FontWidth.Normal;m.slant=m.slant||c.FontSlant.Upright;return m}function g(m){if(!m||!m.length)return I;for(var x=[],H=0;H<m.length;H++){var L=k(m[H]);x.push(L)}return r(x,"HEAPU32")}function k(m){if(z[m])return z[m];
var x=ea(m)+1,H=c._malloc(x);fa(m,K,H,x);return z[m]=H}function n(m){m._colorPtr=F(m.color);m._foregroundColorPtr=I;m._backgroundColorPtr=I;m._decorationColorPtr=I;m.foregroundColor&&(m._foregroundColorPtr=F(m.foregroundColor,D));m.backgroundColor&&(m._backgroundColorPtr=F(m.backgroundColor,G));m.decorationColor&&(m._decorationColorPtr=F(m.decorationColor,J));Array.isArray(m.fontFamilies)&&m.fontFamilies.length?(m._fontFamiliesPtr=g(m.fontFamilies),m._fontFamiliesLen=m.fontFamilies.length):(m._fontFamiliesPtr=
I,m._fontFamiliesLen=0);if(m.locale){var x=m.locale;m._localePtr=k(x);m._localeLen=ea(x)+1}else m._localePtr=I,m._localeLen=0;if(Array.isArray(m.shadows)&&m.shadows.length){x=m.shadows;var H=x.map(function(S){return S.color||c.BLACK}),L=x.map(function(S){return S.blurRadius||0});m._shadowLen=x.length;for(var Z=c._malloc(8*x.length),ma=Z/4,na=0;na<x.length;na++){var ra=x[na].offset||[0,0];c.HEAPF32[ma]=ra[0];c.HEAPF32[ma+1]=ra[1];ma+=2}m._shadowColorsPtr=y(H).hb;m._shadowOffsetsPtr=Z;m._shadowBlurRadiiPtr=
r(L,"HEAPF32")}else m._shadowLen=0,m._shadowColorsPtr=I,m._shadowOffsetsPtr=I,m._shadowBlurRadiiPtr=I;Array.isArray(m.fontFeatures)&&m.fontFeatures.length?(x=m.fontFeatures,H=x.map(function(S){return S.name}),L=x.map(function(S){return S.value}),m._fontFeatureLen=x.length,m._fontFeatureNamesPtr=g(H),m._fontFeatureValuesPtr=r(L,"HEAPU32")):(m._fontFeatureLen=0,m._fontFeatureNamesPtr=I,m._fontFeatureValuesPtr=I);Array.isArray(m.fontVariations)&&m.fontVariations.length?(x=m.fontVariations,H=x.map(function(S){return S.axis}),
L=x.map(function(S){return S.value}),m._fontVariationLen=x.length,m._fontVariationAxesPtr=g(H),m._fontVariationValuesPtr=r(L,"HEAPF32")):(m._fontVariationLen=0,m._fontVariationAxesPtr=I,m._fontVariationValuesPtr=I)}function v(m){c._free(m._fontFamiliesPtr);c._free(m._shadowColorsPtr);c._free(m._shadowOffsetsPtr);c._free(m._shadowBlurRadiiPtr);c._free(m._fontFeatureNamesPtr);c._free(m._fontFeatureValuesPtr)}c.Paragraph.prototype.getRectsForRange=function(m,x,H,L){m=this._getRectsForRange(m,x,H,L);
return b(m)};c.Paragraph.prototype.getRectsForPlaceholders=function(){var m=this._getRectsForPlaceholders();return b(m)};c.TypefaceFontProvider.prototype.registerFont=function(m,x){m=c.Typeface.MakeFreeTypeFaceFromData(m);if(!m)return null;x=k(x);this._registerFont(m,x)};c.ParagraphStyle=function(m){m.disableHinting=m.disableHinting||!1;if(m.ellipsis){var x=m.ellipsis;m._ellipsisPtr=k(x);m._ellipsisLen=ea(x)+1}else m._ellipsisPtr=I,m._ellipsisLen=0;m.heightMultiplier=m.heightMultiplier||0;m.maxLines=
m.maxLines||0;x=(x=m.strutStyle)||{};x.strutEnabled=x.strutEnabled||!1;x.strutEnabled&&Array.isArray(x.fontFamilies)&&x.fontFamilies.length?(x._fontFamiliesPtr=g(x.fontFamilies),x._fontFamiliesLen=x.fontFamilies.length):(x._fontFamiliesPtr=I,x._fontFamiliesLen=0);x.fontStyle=d(x.fontStyle);x.fontSize=x.fontSize||0;x.heightMultiplier=x.heightMultiplier||0;x.halfLeading=x.halfLeading||!1;x.leading=x.leading||0;x.forceStrutHeight=x.forceStrutHeight||!1;m.strutStyle=x;m.textAlign=m.textAlign||c.TextAlign.Start;
m.textDirection=m.textDirection||c.TextDirection.LTR;m.textHeightBehavior=m.textHeightBehavior||c.TextHeightBehavior.All;m.textStyle=c.TextStyle(m.textStyle);return m};c.TextStyle=function(m){m.color||(m.color=c.BLACK);m.decoration=m.decoration||0;m.decorationThickness=m.decorationThickness||0;m.decorationStyle=m.decorationStyle||c.DecorationStyle.Solid;m.textBaseline=m.textBaseline||c.TextBaseline.Alphabetic;m.fontSize=m.fontSize||0;m.letterSpacing=m.letterSpacing||0;m.wordSpacing=m.wordSpacing||
0;m.heightMultiplier=m.heightMultiplier||0;m.halfLeading=m.halfLeading||!1;m.fontStyle=d(m.fontStyle);return m};var z={},D=c._malloc(16),G=c._malloc(16),J=c._malloc(16);c.ParagraphBuilder.Make=function(m,x){n(m.textStyle);x=c.ParagraphBuilder._Make(m,x);v(m.textStyle);return x};c.ParagraphBuilder.MakeFromFontProvider=function(m,x){n(m.textStyle);x=c.ParagraphBuilder._MakeFromFontProvider(m,x);v(m.textStyle);return x};c.ParagraphBuilder.ShapeText=function(m,x,H){let L=0;for(const Z of x)L+=Z.length;
if(L!==m.length)throw"Accumulated block lengths must equal text.length";return c.ParagraphBuilder._ShapeText(m,x,H)};c.ParagraphBuilder.prototype.pushStyle=function(m){n(m);this._pushStyle(m);v(m)};c.ParagraphBuilder.prototype.pushPaintStyle=function(m,x,H){n(m);this._pushPaintStyle(m,x,H);v(m)};c.ParagraphBuilder.prototype.addPlaceholder=function(m,x,H,L,Z){H=H||c.PlaceholderAlignment.Baseline;L=L||c.TextBaseline.Alphabetic;this._addPlaceholder(m||0,x||0,H,L,Z||0)}})})(p);a.MakeManagedAnimation=
function(c,b,d,g,k){if(!a._MakeManagedAnimation)throw"Not compiled with MakeManagedAnimation";d||(d="");if(!b)return a._MakeManagedAnimation(c,0,I,I,I,d,g,k);for(var n=[],v=[],z=[],D=Object.keys(b||{}),G=0;G<D.length;G++){var J=D[G],m=new Uint8Array(b[J]),x=a._malloc(m.byteLength);a.HEAPU8.set(m,x);v.push(x);z.push(m.byteLength);m=ea(J)+1;x=a._malloc(m);fa(J,K,x,m);n.push(x)}b=r(n,"HEAPU32");v=r(v,"HEAPU32");z=r(z,"HEAPU32");c=a._MakeManagedAnimation(c,D.length,b,v,z,d,g,k);a._free(b);a._free(v);
a._free(z);return c};(function(c){c.bb=c.bb||[];c.bb.push(function(){c.Animation.prototype.render=function(b,d){E(d,M);this._render(b,M)};c.Animation.prototype.size=function(b){this._size(M);var d=Y.toTypedArray();return b?(b[0]=d[0],b[1]=d[1],b):d.slice(0,2)};c.ManagedAnimation&&(c.ManagedAnimation.prototype.render=function(b,d){E(d,M);this._render(b,M)},c.ManagedAnimation.prototype.seek=function(b,d){this._seek(b,M);b=Y.toTypedArray();return d?(d.set(b),d):b.slice()},c.ManagedAnimation.prototype.seekFrame=
function(b,d){this._seekFrame(b,M);b=Y.toTypedArray();return d?(d.set(b),d):b.slice()},c.ManagedAnimation.prototype.setColor=function(b,d){d=F(d);return this._setColor(b,d)},c.ManagedAnimation.prototype.size=function(b){this._size(M);var d=Y.toTypedArray();return b?(b[0]=d[0],b[1]=d[1],b):d.slice(0,2)})})})(p);a.MakeParticles=function(c,b){if(!a._MakeParticles)throw"Not compiled with MakeParticles";if(!b)return a._MakeParticles(c,0,I,I,I);for(var d=[],g=[],k=[],n=Object.keys(b||{}),v=0;v<n.length;v++){var z=
n[v],D=new Uint8Array(b[z]),G=a._malloc(D.byteLength);a.HEAPU8.set(D,G);g.push(G);k.push(D.byteLength);D=ea(z)+1;G=a._malloc(D);fa(z,K,G,D);d.push(G)}b=r(d,"HEAPU32");g=r(g,"HEAPU32");k=r(k,"HEAPU32");c=a._MakeParticles(c,n.length,b,g,k);a._free(b);a._free(g);a._free(k);return c};a.bb=a.bb||[];a.bb.push(function(){a.ParticleEffect.prototype.uniforms=function(){var c=this._uniformPtr(),b=this.getUniformFloatCount();return!c||0>=b?new Float32Array:new Float32Array(a.HEAPU8.buffer,c,b)};a.ParticleEffect.prototype.setPosition=
function(c){this._setPosition(c[0],c[1])}});a.bb=a.bb||[];a.bb.push(function(){a.Path.prototype.op=function(c,b){return this._op(c,b)?this:null};a.Path.prototype.simplify=function(){return this._simplify()?this:null}});a.bb=a.bb||[];a.bb.push(function(){a.Canvas.prototype.drawText=function(c,b,d,g,k){var n=ea(c),v=a._malloc(n+1);fa(c,K,v,n+1);this._drawSimpleText(v,n,b,d,k,g);a._free(v)};a.Canvas.prototype.drawGlyphs=function(c,b,d,g,k,n){if(!(2*c.length<=b.length))throw"Not enough positions for the array of gyphs";
const v=r(c,"HEAPU16"),z=r(b,"HEAPF32");this._drawGlyphs(c.length,v,z,d,g,k,n);t(z,b);t(v,c)};a.Font.prototype.getGlyphBounds=function(c,b,d){var g=r(c,"HEAPU16"),k=a._malloc(16*c.length);this._getGlyphWidthBounds(g,c.length,I,k,b||null);b=new Float32Array(a.HEAPU8.buffer,k,4*c.length);t(g,c);if(d)return d.set(b),a._free(k),d;c=Float32Array.from(b);a._free(k);return c};a.Font.prototype.getGlyphIDs=function(c,b,d){b||(b=c.length);var g=ea(c)+1,k=a._malloc(g);fa(c,K,k,g);c=a._malloc(2*b);b=this._getGlyphIDs(k,
g-1,b,c);a._free(k);if(0>b)return a._free(c),null;k=new Uint16Array(a.HEAPU8.buffer,c,b);if(d)return d.set(k),a._free(c),d;d=Uint16Array.from(k);a._free(c);return d};a.Font.prototype.getGlyphIntercepts=function(c,b,d,g){var k=r(c,"HEAPU16"),n=r(b,"HEAPF32");return this._getGlyphIntercepts(k,c.length,!(c&&c._ck),n,b.length,!(b&&b._ck),d,g)};a.Font.prototype.getGlyphWidths=function(c,b,d){var g=r(c,"HEAPU16"),k=a._malloc(4*c.length);this._getGlyphWidthBounds(g,c.length,k,I,b||null);b=new Float32Array(a.HEAPU8.buffer,
k,c.length);t(g,c);if(d)return d.set(b),a._free(k),d;c=Float32Array.from(b);a._free(k);return c};a.FontMgr.FromData=function(){if(!arguments.length)return null;var c=arguments;1===c.length&&Array.isArray(c[0])&&(c=arguments[0]);if(!c.length)return null;for(var b=[],d=[],g=0;g<c.length;g++){var k=new Uint8Array(c[g]),n=r(k,"HEAPU8");b.push(n);d.push(k.byteLength)}b=r(b,"HEAPU32");d=r(d,"HEAPU32");c=a.FontMgr._fromData(b,d,c.length);a._free(b);a._free(d);return c};a.Typeface.MakeFreeTypeFaceFromData=
function(c){c=new Uint8Array(c);var b=r(c,"HEAPU8");return(c=a.Typeface._MakeFreeTypeFaceFromData(b,c.byteLength))?c:null};a.Typeface.prototype.getGlyphIDs=function(c,b,d){b||(b=c.length);var g=ea(c)+1,k=a._malloc(g);fa(c,K,k,g);c=a._malloc(2*b);b=this._getGlyphIDs(k,g-1,b,c);a._free(k);if(0>b)return a._free(c),null;k=new Uint16Array(a.HEAPU8.buffer,c,b);if(d)return d.set(k),a._free(c),d;d=Uint16Array.from(k);a._free(c);return d};a.TextBlob.MakeOnPath=function(c,b,d,g){if(c&&c.length&&b&&b.countPoints()){if(1===
b.countPoints())return this.MakeFromText(c,d);g||(g=0);var k=d.getGlyphIDs(c);k=d.getGlyphWidths(k);var n=[];b=new a.ContourMeasureIter(b,!1,1);for(var v=b.next(),z=new Float32Array(4),D=0;D<c.length&&v;D++){var G=k[D];g+=G/2;if(g>v.length()){v.delete();v=b.next();if(!v){c=c.substring(0,D);break}g=G/2}v.getPosTan(g,z);var J=z[2],m=z[3];n.push(J,m,z[0]-G/2*J,z[1]-G/2*m);g+=G/2}c=this.MakeFromRSXform(c,n,d);v&&v.delete();b.delete();return c}};a.TextBlob.MakeFromRSXform=function(c,b,d){var g=ea(c)+1,
k=a._malloc(g);fa(c,K,k,g);c=r(b,"HEAPF32");d=a.TextBlob._MakeFromRSXform(k,g-1,c,d);a._free(k);return d?d:null};a.TextBlob.MakeFromRSXformGlyphs=function(c,b,d){var g=r(c,"HEAPU16");b=r(b,"HEAPF32");d=a.TextBlob._MakeFromRSXformGlyphs(g,2*c.length,b,d);t(g,c);return d?d:null};a.TextBlob.MakeFromGlyphs=function(c,b){var d=r(c,"HEAPU16");b=a.TextBlob._MakeFromGlyphs(d,2*c.length,b);t(d,c);return b?b:null};a.TextBlob.MakeFromText=function(c,b){var d=ea(c)+1,g=a._malloc(d);fa(c,K,g,d);c=a.TextBlob._MakeFromText(g,
d-1,b);a._free(g);return c?c:null};a.MallocGlyphIDs=function(c){return a.Malloc(Uint16Array,c)}});a.bb=a.bb||[];a.bb.push(function(){a.MakePicture=function(c){c=new Uint8Array(c);var b=a._malloc(c.byteLength);a.HEAPU8.set(c,b);return(c=a._MakePicture(b,c.byteLength))?c:null}});a.bb=a.bb||[];a.bb.push(function(){a.RuntimeEffect.Make=function(c,b){return a.RuntimeEffect._Make(c,{onError:b||function(d){console.log("RuntimeEffect error",d)}})};a.RuntimeEffect.prototype.makeShader=function(c,b){var d=
!c._ck,g=r(c,"HEAPF32");b=A(b);return this._makeShader(g,4*c.length,d,b)};a.RuntimeEffect.prototype.makeShaderWithChildren=function(c,b,d){var g=!c._ck,k=r(c,"HEAPF32");d=A(d);for(var n=[],v=0;v<b.length;v++)n.push(b[v].$a.cb);b=r(n,"HEAPU32");return this._makeShaderWithChildren(k,4*c.length,g,b,n.length,d)}})})(p);
var ha=Object.assign({},p),ia="./this.program",la=(a,e)=>{throw e;},oa="object"==typeof window,pa="function"==typeof importScripts,qa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,sa="",ua,wa,xa,fs,ya,za;
if(qa)sa=pa?require("path").dirname(sa)+"/":__dirname+"/",za=()=>{ya||(fs=require("fs"),ya=require("path"))},ua=function(a,e){za();a=ya.normalize(a);return fs.readFileSync(a,e?void 0:"utf8")},xa=a=>{a=ua(a,!0);a.buffer||(a=new Uint8Array(a));return a},wa=(a,e,f)=>{za();a=ya.normalize(a);fs.readFile(a,function(h,l){h?f(h):e(l.buffer)})},1<process.argv.length&&(ia=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("unhandledRejection",function(a){throw a;}),la=(a,e)=>{if(noExitRuntime)throw process.exitCode=
a,e;e instanceof Aa||Ka("exiting due to exception: "+e);process.exit(a)},p.inspect=function(){return"[Emscripten Module object]"};else if(oa||pa)pa?sa=self.location.href:"undefined"!=typeof document&&document.currentScript&&(sa=document.currentScript.src),_scriptDir&&(sa=_scriptDir),0!==sa.indexOf("blob:")?sa=sa.substr(0,sa.replace(/[?#].*/,"").lastIndexOf("/")+1):sa="",ua=a=>{var e=new XMLHttpRequest;e.open("GET",a,!1);e.send(null);return e.responseText},pa&&(xa=a=>{var e=new XMLHttpRequest;e.open("GET",
a,!1);e.responseType="arraybuffer";e.send(null);return new Uint8Array(e.response)}),wa=(a,e,f)=>{var h=new XMLHttpRequest;h.open("GET",a,!0);h.responseType="arraybuffer";h.onload=()=>{200==h.status||0==h.status&&h.response?e(h.response):f()};h.onerror=f;h.send(null)};var La=p.print||console.log.bind(console),Ka=p.printErr||console.warn.bind(console);Object.assign(p,ha);ha=null;p.thisProgram&&(ia=p.thisProgram);p.quit&&(la=p.quit);var Oa=0,Pa;p.wasmBinary&&(Pa=p.wasmBinary);
var noExitRuntime=p.noExitRuntime||!0;"object"!=typeof WebAssembly&&Qa("no native wasm support detected");var Ra,Sa=!1,Ta="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ua(a,e,f){var h=e+f;for(f=e;a[f]&&!(f>=h);)++f;if(16<f-e&&a.buffer&&Ta)return Ta.decode(a.subarray(e,f));for(h="";e<f;){var l=a[e++];if(l&128){var q=a[e++]&63;if(192==(l&224))h+=String.fromCharCode((l&31)<<6|q);else{var w=a[e++]&63;l=224==(l&240)?(l&15)<<12|q<<6|w:(l&7)<<18|q<<12|w<<6|a[e++]&63;65536>l?h+=String.fromCharCode(l):(l-=65536,h+=String.fromCharCode(55296|l>>10,56320|l&1023))}}else h+=String.fromCharCode(l)}return h}
function fa(a,e,f,h){if(0<h){h=f+h-1;for(var l=0;l<a.length;++l){var q=a.charCodeAt(l);if(55296<=q&&57343>=q){var w=a.charCodeAt(++l);q=65536+((q&1023)<<10)|w&1023}if(127>=q){if(f>=h)break;e[f++]=q}else{if(2047>=q){if(f+1>=h)break;e[f++]=192|q>>6}else{if(65535>=q){if(f+2>=h)break;e[f++]=224|q>>12}else{if(f+3>=h)break;e[f++]=240|q>>18;e[f++]=128|q>>12&63}e[f++]=128|q>>6&63}e[f++]=128|q&63}}e[f]=0}}
function ea(a){for(var e=0,f=0;f<a.length;++f){var h=a.charCodeAt(f);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++f)&1023);127>=h?++e:e=2047>=h?e+2:65535>=h?e+3:e+4}return e}var Va="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function Wa(a,e){var f=a>>1;for(var h=f+e/2;!(f>=h)&&Xa[f];)++f;f<<=1;if(32<f-a&&Va)return Va.decode(K.subarray(a,f));f="";for(h=0;!(h>=e/2);++h){var l=Ya[a+2*h>>1];if(0==l)break;f+=String.fromCharCode(l)}return f}
function Za(a,e,f){void 0===f&&(f=2147483647);if(2>f)return 0;f-=2;var h=e;f=f<2*a.length?f/2:a.length;for(var l=0;l<f;++l)Ya[e>>1]=a.charCodeAt(l),e+=2;Ya[e>>1]=0;return e-h}function ab(a){return 2*a.length}function bb(a,e){for(var f=0,h="";!(f>=e/4);){var l=O[a+4*f>>2];if(0==l)break;++f;65536<=l?(l-=65536,h+=String.fromCharCode(55296|l>>10,56320|l&1023)):h+=String.fromCharCode(l)}return h}
function cb(a,e,f){void 0===f&&(f=2147483647);if(4>f)return 0;var h=e;f=h+f-4;for(var l=0;l<a.length;++l){var q=a.charCodeAt(l);if(55296<=q&&57343>=q){var w=a.charCodeAt(++l);q=65536+((q&1023)<<10)|w&1023}O[e>>2]=q;e+=4;if(e+4>f)break}O[e>>2]=0;return e-h}function db(a){for(var e=0,f=0;f<a.length;++f){var h=a.charCodeAt(f);55296<=h&&57343>=h&&++f;e+=4}return e}var eb,fb,K,Ya,Xa,O,P,gb,hb;
function ib(){var a=Ra.buffer;eb=a;p.HEAP8=fb=new Int8Array(a);p.HEAP16=Ya=new Int16Array(a);p.HEAP32=O=new Int32Array(a);p.HEAPU8=K=new Uint8Array(a);p.HEAPU16=Xa=new Uint16Array(a);p.HEAPU32=P=new Uint32Array(a);p.HEAPF32=gb=new Float32Array(a);p.HEAPF64=hb=new Float64Array(a)}var jb,kb=[],lb=[],mb=[];function nb(){var a=p.preRun.shift();kb.unshift(a)}var ob=0,pb=null,qb=null;
function Qa(a){if(p.onAbort)p.onAbort(a);a="Aborted("+a+")";Ka(a);Sa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");da(a);throw a;}function zb(){return Ab.startsWith("data:application/octet-stream;base64,")}var Ab;Ab="canvaskit.wasm";if(!zb()){var Bb=Ab;Ab=p.locateFile?p.locateFile(Bb,sa):sa+Bb}function Cb(){var a=Ab;try{if(a==Ab&&Pa)return new Uint8Array(Pa);if(xa)return xa(a);throw"both async and sync fetching of the wasm failed";}catch(e){Qa(e)}}
function Db(){if(!Pa&&(oa||pa)){if("function"==typeof fetch&&!Ab.startsWith("file://"))return fetch(Ab,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ab+"'";return a.arrayBuffer()}).catch(function(){return Cb()});if(wa)return new Promise(function(a,e){wa(Ab,function(f){a(new Uint8Array(f))},e)})}return Promise.resolve().then(function(){return Cb()})}function Eb(a){for(;0<a.length;)a.shift()(p)}function Q(a){return jb.get(a)}var Fb={};
function Gb(a){for(;a.length;){var e=a.pop();a.pop()(e)}}function Hb(a){return this.fromWireType(O[a>>2])}var Ib={},Jb={},Kb={};function Lb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var e=a.charCodeAt(0);return 48<=e&&57>=e?"_"+a:a}function Mb(a,e){a=Lb(a);return function(){null;return e.apply(this,arguments)}}
function Nb(a){var e=Error,f=Mb(a,function(h){this.name=a;this.message=h;h=Error(h).stack;void 0!==h&&(this.stack=this.toString()+"\n"+h.replace(/^Error(:[^\n]*)?\n/,""))});f.prototype=Object.create(e.prototype);f.prototype.constructor=f;f.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return f}var Ob=void 0;function Pb(a){throw new Ob(a);}
function Qb(a,e,f){function h(t){t=f(t);t.length!==a.length&&Pb("Mismatched type converter count");for(var r=0;r<a.length;++r)Rb(a[r],t[r])}a.forEach(function(t){Kb[t]=e});var l=Array(e.length),q=[],w=0;e.forEach((t,r)=>{Jb.hasOwnProperty(t)?l[r]=Jb[t]:(q.push(t),Ib.hasOwnProperty(t)||(Ib[t]=[]),Ib[t].push(()=>{l[r]=Jb[t];++w;w===q.length&&h(l)}))});0===q.length&&h(l)}
function Sb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Tb=void 0;function R(a){for(var e="";K[a];)e+=Tb[K[a++]];return e}var Ub=void 0;function T(a){throw new Ub(a);}
function Rb(a,e,f={}){if(!("argPackAdvance"in e))throw new TypeError("registerType registeredInstance requires argPackAdvance");var h=e.name;a||T('type "'+h+'" must have a positive integer typeid pointer');if(Jb.hasOwnProperty(a)){if(f.ac)return;T("Cannot register type '"+h+"' twice")}Jb[a]=e;delete Kb[a];Ib.hasOwnProperty(a)&&(e=Ib[a],delete Ib[a],e.forEach(l=>l()))}function Vb(a){T(a.$a.eb.ab.name+" instance already deleted")}var Wb=!1;function Xb(){}
function Yb(a){--a.count.value;0===a.count.value&&(a.gb?a.jb.mb(a.gb):a.eb.ab.mb(a.cb))}function Zb(a,e,f){if(e===f)return a;if(void 0===f.kb)return null;a=Zb(a,e,f.kb);return null===a?null:f.Ub(a)}var gc={},hc=[];function ic(){for(;hc.length;){var a=hc.pop();a.$a.sb=!1;a["delete"]()}}var jc=void 0,kc={};function lc(a,e){for(void 0===e&&T("ptr should not be undefined");a.kb;)e=a.xb(e),a=a.kb;return kc[e]}
function mc(a,e){e.eb&&e.cb||Pb("makeClassHandle requires ptr and ptrType");!!e.jb!==!!e.gb&&Pb("Both smartPtrType and smartPtr must be specified");e.count={value:1};return nc(Object.create(a,{$a:{value:e}}))}function nc(a){if("undefined"===typeof FinalizationRegistry)return nc=e=>e,a;Wb=new FinalizationRegistry(e=>{Yb(e.$a)});nc=e=>{var f=e.$a;f.gb&&Wb.register(e,{$a:f},e);return e};Xb=e=>{Wb.unregister(e)};return nc(a)}function oc(){}
function pc(a,e,f){if(void 0===a[e].fb){var h=a[e];a[e]=function(){a[e].fb.hasOwnProperty(arguments.length)||T("Function '"+f+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[e].fb+")!");return a[e].fb[arguments.length].apply(this,arguments)};a[e].fb=[];a[e].fb[h.rb]=h}}
function qc(a,e,f){p.hasOwnProperty(a)?((void 0===f||void 0!==p[a].fb&&void 0!==p[a].fb[f])&&T("Cannot register public name '"+a+"' twice"),pc(p,a,a),p.hasOwnProperty(f)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+f+")!"),p[a].fb[f]=e):(p[a]=e,void 0!==f&&(p[a].pc=f))}function rc(a,e,f,h,l,q,w,t){this.name=a;this.constructor=e;this.tb=f;this.mb=h;this.kb=l;this.Wb=q;this.xb=w;this.Ub=t;this.dc=[]}
function sc(a,e,f){for(;e!==f;)e.xb||T("Expected null or instance of "+f.name+", got an instance of "+e.name),a=e.xb(a),e=e.kb;return a}function tc(a,e){if(null===e)return this.Eb&&T("null is not a valid "+this.name),0;e.$a||T('Cannot pass "'+uc(e)+'" as a '+this.name);e.$a.cb||T("Cannot pass deleted object as a pointer of type "+this.name);return sc(e.$a.cb,e.$a.eb.ab,this.ab)}
function vc(a,e){if(null===e){this.Eb&&T("null is not a valid "+this.name);if(this.Ab){var f=this.Fb();null!==a&&a.push(this.mb,f);return f}return 0}e.$a||T('Cannot pass "'+uc(e)+'" as a '+this.name);e.$a.cb||T("Cannot pass deleted object as a pointer of type "+this.name);!this.zb&&e.$a.eb.zb&&T("Cannot convert argument of type "+(e.$a.jb?e.$a.jb.name:e.$a.eb.name)+" to parameter type "+this.name);f=sc(e.$a.cb,e.$a.eb.ab,this.ab);if(this.Ab)switch(void 0===e.$a.gb&&T("Passing raw pointer to smart pointer is illegal"),
this.kc){case 0:e.$a.jb===this?f=e.$a.gb:T("Cannot convert argument of type "+(e.$a.jb?e.$a.jb.name:e.$a.eb.name)+" to parameter type "+this.name);break;case 1:f=e.$a.gb;break;case 2:if(e.$a.jb===this)f=e.$a.gb;else{var h=e.clone();f=this.ec(f,wc(function(){h["delete"]()}));null!==a&&a.push(this.mb,f)}break;default:T("Unsupporting sharing policy")}return f}
function xc(a,e){if(null===e)return this.Eb&&T("null is not a valid "+this.name),0;e.$a||T('Cannot pass "'+uc(e)+'" as a '+this.name);e.$a.cb||T("Cannot pass deleted object as a pointer of type "+this.name);e.$a.eb.zb&&T("Cannot convert argument of type "+e.$a.eb.name+" to parameter type "+this.name);return sc(e.$a.cb,e.$a.eb.ab,this.ab)}
function yc(a,e,f,h,l,q,w,t,r,y,A){this.name=a;this.ab=e;this.Eb=f;this.zb=h;this.Ab=l;this.cc=q;this.kc=w;this.Kb=t;this.Fb=r;this.ec=y;this.mb=A;l||void 0!==e.kb?this.toWireType=vc:(this.toWireType=h?tc:xc,this.ib=null)}function zc(a,e,f){p.hasOwnProperty(a)||Pb("Replacing nonexistant public symbol");void 0!==p[a].fb&&void 0!==f?p[a].fb[f]=e:(p[a]=e,p[a].rb=f)}
function Ac(a,e){var f=[];return function(){f.length=0;Object.assign(f,arguments);if(a.includes("j")){var h=p["dynCall_"+a];h=f&&f.length?h.apply(null,[e].concat(f)):h.call(null,e)}else h=Q(e).apply(null,f);return h}}function U(a,e){a=R(a);var f=a.includes("j")?Ac(a,e):Q(e);"function"!=typeof f&&T("unknown function pointer with signature "+a+": "+e);return f}var Bc=void 0;function Cc(a){a=Dc(a);var e=R(a);Ec(a);return e}
function Fc(a,e){function f(q){l[q]||Jb[q]||(Kb[q]?Kb[q].forEach(f):(h.push(q),l[q]=!0))}var h=[],l={};e.forEach(f);throw new Bc(a+": "+h.map(Cc).join([", "]));}
function Gc(a,e,f,h,l){var q=e.length;2>q&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");var w=null!==e[1]&&null!==f,t=!1;for(f=1;f<e.length;++f)if(null!==e[f]&&void 0===e[f].ib){t=!0;break}var r="void"!==e[0].name,y=q-2,A=Array(y),B=[],F=[];return function(){arguments.length!==y&&T("function "+a+" called with "+arguments.length+" arguments, expected "+y+" args!");F.length=0;B.length=w?2:1;B[0]=l;if(w){var u=e[1].toWireType(F,this);B[1]=u}for(var C=0;C<y;++C)A[C]=
e[C+2].toWireType(F,arguments[C]),B.push(A[C]);C=h.apply(null,B);if(t)Gb(F);else for(var E=w?1:2;E<e.length;E++){var N=1===E?u:A[E-2];null!==e[E].ib&&e[E].ib(N)}u=r?e[0].fromWireType(C):void 0;return u}}function Hc(a,e){for(var f=[],h=0;h<a;h++)f.push(P[e+4*h>>2]);return f}var Ic=[],Jc=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Kc(a){4<a&&0===--Jc[a].Gb&&(Jc[a]=void 0,Ic.push(a))}
var Lc=a=>{a||T("Cannot use deleted val. handle = "+a);return Jc[a].value},wc=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var e=Ic.length?Ic.pop():Jc.length;Jc[e]={Gb:1,value:a};return e}};
function Mc(a,e,f){switch(e){case 0:return function(h){return this.fromWireType((f?fb:K)[h])};case 1:return function(h){return this.fromWireType((f?Ya:Xa)[h>>1])};case 2:return function(h){return this.fromWireType((f?O:P)[h>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function Nc(a,e){var f=Jb[a];void 0===f&&T(e+" has unknown type "+Cc(a));return f}function uc(a){if(null===a)return"null";var e=typeof a;return"object"===e||"array"===e||"function"===e?a.toString():""+a}
function Oc(a,e){switch(e){case 2:return function(f){return this.fromWireType(gb[f>>2])};case 3:return function(f){return this.fromWireType(hb[f>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Rc(a,e,f){switch(e){case 0:return f?function(h){return fb[h]}:function(h){return K[h]};case 1:return f?function(h){return Ya[h>>1]}:function(h){return Xa[h>>1]};case 2:return f?function(h){return O[h>>2]}:function(h){return P[h>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Sc={};function Tc(a){var e=Sc[a];return void 0===e?R(a):e}var Uc=[];
function Vc(){function a(e){e.$$$embind_global$$$=e;var f="object"==typeof $$$embind_global$$$&&e.$$$embind_global$$$==e;f||delete e.$$$embind_global$$$;return f}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
}function Wc(a){var e=Uc.length;Uc.push(a);return e}function Xc(a,e){for(var f=Array(a),h=0;h<a;++h)f[h]=Nc(P[e+4*h>>2],"parameter "+h);return f}var Yc=[];function Zc(a){var e=Array(a+1);return function(f,h,l){e[0]=f;for(var q=0;q<a;++q){var w=Nc(P[h+4*q>>2],"parameter "+q);e[q+1]=w.readValueFromPointer(l);l+=w.argPackAdvance}f=new (f.bind.apply(f,e));return wc(f)}}var $c={},ad;ad=qa?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var bd={};
function cd(){if(!dd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ia||"./this.program"},e;for(e in bd)void 0===bd[e]?delete a[e]:a[e]=bd[e];var f=[];for(e in a)f.push(e+"="+a[e]);dd=f}return dd}var dd,ed=[null,[],[]];function fd(a){return 0===a%4&&(0!==a%100||0===a%400)}
var gd=[31,29,31,30,31,30,31,31,30,31,30,31],hd=[31,28,31,30,31,30,31,31,30,31,30,31];
function jd(a,e,f,h){function l(u,C,E){for(u="number"==typeof u?u.toString():u||"";u.length<C;)u=E[0]+u;return u}function q(u,C){return l(u,C,"0")}function w(u,C){function E(ka){return 0>ka?-1:0<ka?1:0}var N;0===(N=E(u.getFullYear()-C.getFullYear()))&&0===(N=E(u.getMonth()-C.getMonth()))&&(N=E(u.getDate()-C.getDate()));return N}function t(u){switch(u.getDay()){case 0:return new Date(u.getFullYear()-1,11,29);case 1:return u;case 2:return new Date(u.getFullYear(),0,3);case 3:return new Date(u.getFullYear(),
0,2);case 4:return new Date(u.getFullYear(),0,1);case 5:return new Date(u.getFullYear()-1,11,31);case 6:return new Date(u.getFullYear()-1,11,30)}}function r(u){var C=u.ob;for(u=new Date((new Date(u.pb+1900,0,1)).getTime());0<C;){var E=u.getMonth(),N=(fd(u.getFullYear())?gd:hd)[E];if(C>N-u.getDate())C-=N-u.getDate()+1,u.setDate(1),11>E?u.setMonth(E+1):(u.setMonth(0),u.setFullYear(u.getFullYear()+1));else{u.setDate(u.getDate()+C);break}}E=new Date(u.getFullYear()+1,0,4);C=t(new Date(u.getFullYear(),
0,4));E=t(E);return 0>=w(C,u)?0>=w(E,u)?u.getFullYear()+1:u.getFullYear():u.getFullYear()-1}var y=O[h+40>>2];h={nc:O[h>>2],mc:O[h+4>>2],Bb:O[h+8>>2],Hb:O[h+12>>2],Cb:O[h+16>>2],pb:O[h+20>>2],lb:O[h+24>>2],ob:O[h+28>>2],qc:O[h+32>>2],lc:O[h+36>>2],oc:y?y?Ua(K,y):"":""};f=f?Ua(K,f):"";y={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var A in y)f=f.replace(new RegExp(A,"g"),y[A]);var B="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),F="January February March April May June July August September October November December".split(" ");y={"%a":function(u){return B[u.lb].substring(0,3)},"%A":function(u){return B[u.lb]},"%b":function(u){return F[u.Cb].substring(0,
3)},"%B":function(u){return F[u.Cb]},"%C":function(u){return q((u.pb+1900)/100|0,2)},"%d":function(u){return q(u.Hb,2)},"%e":function(u){return l(u.Hb,2," ")},"%g":function(u){return r(u).toString().substring(2)},"%G":function(u){return r(u)},"%H":function(u){return q(u.Bb,2)},"%I":function(u){u=u.Bb;0==u?u=12:12<u&&(u-=12);return q(u,2)},"%j":function(u){for(var C=0,E=0;E<=u.Cb-1;C+=(fd(u.pb+1900)?gd:hd)[E++]);return q(u.Hb+C,3)},"%m":function(u){return q(u.Cb+1,2)},"%M":function(u){return q(u.mc,
2)},"%n":function(){return"\n"},"%p":function(u){return 0<=u.Bb&&12>u.Bb?"AM":"PM"},"%S":function(u){return q(u.nc,2)},"%t":function(){return"\t"},"%u":function(u){return u.lb||7},"%U":function(u){return q(Math.floor((u.ob+7-u.lb)/7),2)},"%V":function(u){var C=Math.floor((u.ob+7-(u.lb+6)%7)/7);2>=(u.lb+371-u.ob-2)%7&&C++;if(C)53==C&&(E=(u.lb+371-u.ob)%7,4==E||3==E&&fd(u.pb)||(C=1));else{C=52;var E=(u.lb+7-u.ob-1)%7;(4==E||5==E&&fd(u.pb%400-1))&&C++}return q(C,2)},"%w":function(u){return u.lb},"%W":function(u){return q(Math.floor((u.ob+
7-(u.lb+6)%7)/7),2)},"%y":function(u){return(u.pb+1900).toString().substring(2)},"%Y":function(u){return u.pb+1900},"%z":function(u){u=u.lc;var C=0<=u;u=Math.abs(u)/60;return(C?"+":"-")+String("0000"+(u/60*100+u%60)).slice(-4)},"%Z":function(u){return u.oc},"%%":function(){return"%"}};f=f.replace(/%%/g,"\x00\x00");for(A in y)f.includes(A)&&(f=f.replace(new RegExp(A,"g"),y[A](h)));f=f.replace(/\0\0/g,"%");A=kd(f);if(A.length>e)return 0;fb.set(A,a);return A.length-1}Ob=p.InternalError=Nb("InternalError");
for(var ld=Array(256),md=0;256>md;++md)ld[md]=String.fromCharCode(md);Tb=ld;Ub=p.BindingError=Nb("BindingError");oc.prototype.isAliasOf=function(a){if(!(this instanceof oc&&a instanceof oc))return!1;var e=this.$a.eb.ab,f=this.$a.cb,h=a.$a.eb.ab;for(a=a.$a.cb;e.kb;)f=e.xb(f),e=e.kb;for(;h.kb;)a=h.xb(a),h=h.kb;return e===h&&f===a};
oc.prototype.clone=function(){this.$a.cb||Vb(this);if(this.$a.wb)return this.$a.count.value+=1,this;var a=nc,e=Object,f=e.create,h=Object.getPrototypeOf(this),l=this.$a;a=a(f.call(e,h,{$a:{value:{count:l.count,sb:l.sb,wb:l.wb,cb:l.cb,eb:l.eb,gb:l.gb,jb:l.jb}}}));a.$a.count.value+=1;a.$a.sb=!1;return a};oc.prototype["delete"]=function(){this.$a.cb||Vb(this);this.$a.sb&&!this.$a.wb&&T("Object already scheduled for deletion");Xb(this);Yb(this.$a);this.$a.wb||(this.$a.gb=void 0,this.$a.cb=void 0)};
oc.prototype.isDeleted=function(){return!this.$a.cb};oc.prototype.deleteLater=function(){this.$a.cb||Vb(this);this.$a.sb&&!this.$a.wb&&T("Object already scheduled for deletion");hc.push(this);1===hc.length&&jc&&jc(ic);this.$a.sb=!0;return this};p.getInheritedInstanceCount=function(){return Object.keys(kc).length};p.getLiveInheritedInstances=function(){var a=[],e;for(e in kc)kc.hasOwnProperty(e)&&a.push(kc[e]);return a};p.flushPendingDeletes=ic;p.setDelayFunction=function(a){jc=a;hc.length&&jc&&jc(ic)};
yc.prototype.Xb=function(a){this.Kb&&(a=this.Kb(a));return a};yc.prototype.Ib=function(a){this.mb&&this.mb(a)};yc.prototype.argPackAdvance=8;yc.prototype.readValueFromPointer=Hb;yc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
yc.prototype.fromWireType=function(a){function e(){return this.Ab?mc(this.ab.tb,{eb:this.cc,cb:f,jb:this,gb:a}):mc(this.ab.tb,{eb:this,cb:a})}var f=this.Xb(a);if(!f)return this.Ib(a),null;var h=lc(this.ab,f);if(void 0!==h){if(0===h.$a.count.value)return h.$a.cb=f,h.$a.gb=a,h.clone();h=h.clone();this.Ib(a);return h}h=this.ab.Wb(f);h=gc[h];if(!h)return e.call(this);h=this.zb?h.Sb:h.pointerType;var l=Zb(f,this.ab,h.ab);return null===l?e.call(this):this.Ab?mc(h.ab.tb,{eb:h,cb:l,jb:this,gb:a}):mc(h.ab.tb,
{eb:h,cb:l})};Bc=p.UnboundTypeError=Nb("UnboundTypeError");p.count_emval_handles=function(){for(var a=0,e=5;e<Jc.length;++e)void 0!==Jc[e]&&++a;return a};p.get_first_emval=function(){for(var a=5;a<Jc.length;++a)if(void 0!==Jc[a])return Jc[a];return null};function kd(a){var e=Array(ea(a)+1);fa(a,e,0,e.length);return e}
var Dd={S:function(){return 0},ja:function(){},la:function(){return 0},ga:function(){},ha:function(){},T:function(){},ia:function(){},D:function(a){var e=Fb[a];delete Fb[a];var f=e.Fb,h=e.mb,l=e.Jb,q=l.map(w=>w.$b).concat(l.map(w=>w.ic));Qb([a],q,w=>{var t={};l.forEach((r,y)=>{var A=w[y],B=r.Yb,F=r.Zb,u=w[y+l.length],C=r.hc,E=r.jc;t[r.Vb]={read:N=>A.fromWireType(B(F,N)),write:(N,ka)=>{var ba=[];C(E,N,u.toWireType(ba,ka));Gb(ba)}}});return[{name:e.name,fromWireType:function(r){var y={},A;for(A in t)y[A]=
t[A].read(r);h(r);return y},toWireType:function(r,y){for(var A in t)if(!(A in y))throw new TypeError('Missing field:  "'+A+'"');var B=f();for(A in t)t[A].write(B,y[A]);null!==r&&r.push(h,B);return B},argPackAdvance:8,readValueFromPointer:Hb,ib:h}]})},_:function(){},pa:function(a,e,f,h,l){var q=Sb(f);e=R(e);Rb(a,{name:e,fromWireType:function(w){return!!w},toWireType:function(w,t){return t?h:l},argPackAdvance:8,readValueFromPointer:function(w){if(1===f)var t=fb;else if(2===f)t=Ya;else if(4===f)t=O;
else throw new TypeError("Unknown boolean type size: "+e);return this.fromWireType(t[w>>q])},ib:null})},q:function(a,e,f,h,l,q,w,t,r,y,A,B,F){A=R(A);q=U(l,q);t&&(t=U(w,t));y&&(y=U(r,y));F=U(B,F);var u=Lb(A);qc(u,function(){Fc("Cannot construct "+A+" due to unbound types",[h])});Qb([a,e,f],h?[h]:[],function(C){C=C[0];if(h){var E=C.ab;var N=E.tb}else N=oc.prototype;C=Mb(u,function(){if(Object.getPrototypeOf(this)!==ka)throw new Ub("Use 'new' to construct "+A);if(void 0===ba.nb)throw new Ub(A+" has no accessible constructor");
var ja=ba.nb[arguments.length];if(void 0===ja)throw new Ub("Tried to invoke ctor of "+A+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(ba.nb).toString()+") parameters instead!");return ja.apply(this,arguments)});var ka=Object.create(N,{constructor:{value:C}});C.prototype=ka;var ba=new rc(A,C,ka,F,E,q,t,y);E=new yc(A,ba,!0,!1,!1);N=new yc(A+"*",ba,!1,!1,!1);var Ma=new yc(A+" const*",ba,!1,!0,!1);gc[a]={pointerType:N,Sb:Ma};zc(u,C);return[E,N,Ma]})},i:function(a,
e,f,h,l,q,w){var t=Hc(f,h);e=R(e);q=U(l,q);Qb([],[a],function(r){function y(){Fc("Cannot call "+A+" due to unbound types",t)}r=r[0];var A=r.name+"."+e;e.startsWith("@@")&&(e=Symbol[e.substring(2)]);var B=r.ab.constructor;void 0===B[e]?(y.rb=f-1,B[e]=y):(pc(B,e,A),B[e].fb[f-1]=y);Qb([],t,function(F){F=[F[0],null].concat(F.slice(1));F=Gc(A,F,null,q,w);void 0===B[e].fb?(F.rb=f-1,B[e]=F):B[e].fb[f-1]=F;return[]});return[]})},F:function(a,e,f,h,l,q){0<e||Qa();var w=Hc(e,f);l=U(h,l);Qb([],[a],function(t){t=
t[0];var r="constructor "+t.name;void 0===t.ab.nb&&(t.ab.nb=[]);if(void 0!==t.ab.nb[e-1])throw new Ub("Cannot register multiple constructors with identical number of parameters ("+(e-1)+") for class '"+t.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");t.ab.nb[e-1]=()=>{Fc("Cannot construct "+t.name+" due to unbound types",w)};Qb([],w,function(y){y.splice(1,0,null);t.ab.nb[e-1]=Gc(r,y,null,l,q);return[]});return[]})},b:function(a,e,f,h,l,
q,w,t){var r=Hc(f,h);e=R(e);q=U(l,q);Qb([],[a],function(y){function A(){Fc("Cannot call "+B+" due to unbound types",r)}y=y[0];var B=y.name+"."+e;e.startsWith("@@")&&(e=Symbol[e.substring(2)]);t&&y.ab.dc.push(e);var F=y.ab.tb,u=F[e];void 0===u||void 0===u.fb&&u.className!==y.name&&u.rb===f-2?(A.rb=f-2,A.className=y.name,F[e]=A):(pc(F,e,B),F[e].fb[f-2]=A);Qb([],r,function(C){C=Gc(B,C,y,q,w);void 0===F[e].fb?(C.rb=f-2,F[e]=C):F[e].fb[f-2]=C;return[]});return[]})},u:function(a,e,f){a=R(a);Qb([],[e],function(h){h=
h[0];p[a]=h.fromWireType(f);return[]})},oa:function(a,e){e=R(e);Rb(a,{name:e,fromWireType:function(f){var h=Lc(f);Kc(f);return h},toWireType:function(f,h){return wc(h)},argPackAdvance:8,readValueFromPointer:Hb,ib:null})},o:function(a,e,f,h){function l(){}f=Sb(f);e=R(e);l.values={};Rb(a,{name:e,constructor:l,fromWireType:function(q){return this.constructor.values[q]},toWireType:function(q,w){return w.value},argPackAdvance:8,readValueFromPointer:Mc(e,f,h),ib:null});qc(e,l)},f:function(a,e,f){var h=
Nc(a,"enum");e=R(e);a=h.constructor;h=Object.create(h.constructor.prototype,{value:{value:f},constructor:{value:Mb(h.name+"_"+e,function(){})}});a.values[f]=h;a[e]=h},V:function(a,e,f){f=Sb(f);e=R(e);Rb(a,{name:e,fromWireType:function(h){return h},toWireType:function(h,l){return l},argPackAdvance:8,readValueFromPointer:Oc(e,f),ib:null})},A:function(a,e,f,h,l,q){var w=Hc(e,f);a=R(a);l=U(h,l);qc(a,function(){Fc("Cannot call "+a+" due to unbound types",w)},e-1);Qb([],w,function(t){t=[t[0],null].concat(t.slice(1));
zc(a,Gc(a,t,null,l,q),e-1);return[]})},G:function(a,e,f,h,l){e=R(e);-1===l&&(l=4294967295);l=Sb(f);var q=t=>t;if(0===h){var w=32-8*f;q=t=>t<<w>>>w}f=e.includes("unsigned")?function(t,r){return r>>>0}:function(t,r){return r};Rb(a,{name:e,fromWireType:q,toWireType:f,argPackAdvance:8,readValueFromPointer:Rc(e,l,0!==h),ib:null})},w:function(a,e,f){function h(q){q>>=2;var w=P;return new l(eb,w[q+1],w[q])}var l=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][e];
f=R(f);Rb(a,{name:f,fromWireType:h,argPackAdvance:8,readValueFromPointer:h},{ac:!0})},t:function(a,e,f,h,l,q,w,t,r,y,A,B){f=R(f);q=U(l,q);t=U(w,t);y=U(r,y);B=U(A,B);Qb([a],[e],function(F){F=F[0];return[new yc(f,F.ab,!1,!1,!0,F,h,q,t,y,B)]})},U:function(a,e){e=R(e);var f="std::string"===e;Rb(a,{name:e,fromWireType:function(h){var l=P[h>>2],q=h+4;if(f)for(var w=q,t=0;t<=l;++t){var r=q+t;if(t==l||0==K[r]){w=w?Ua(K,w,r-w):"";if(void 0===y)var y=w;else y+=String.fromCharCode(0),y+=w;w=r+1}}else{y=Array(l);
for(t=0;t<l;++t)y[t]=String.fromCharCode(K[q+t]);y=y.join("")}Ec(h);return y},toWireType:function(h,l){l instanceof ArrayBuffer&&(l=new Uint8Array(l));var q="string"==typeof l;q||l instanceof Uint8Array||l instanceof Uint8ClampedArray||l instanceof Int8Array||T("Cannot pass non-string to std::string");var w=f&&q?ea(l):l.length;var t=nd(4+w+1),r=t+4;P[t>>2]=w;if(f&&q)fa(l,K,r,w+1);else if(q)for(q=0;q<w;++q){var y=l.charCodeAt(q);255<y&&(Ec(r),T("String has UTF-16 code units that do not fit in 8 bits"));
K[r+q]=y}else for(q=0;q<w;++q)K[r+q]=l[q];null!==h&&h.push(Ec,t);return t},argPackAdvance:8,readValueFromPointer:Hb,ib:function(h){Ec(h)}})},O:function(a,e,f){f=R(f);if(2===e){var h=Wa;var l=Za;var q=ab;var w=()=>Xa;var t=1}else 4===e&&(h=bb,l=cb,q=db,w=()=>P,t=2);Rb(a,{name:f,fromWireType:function(r){for(var y=P[r>>2],A=w(),B,F=r+4,u=0;u<=y;++u){var C=r+4+u*e;if(u==y||0==A[C>>t])F=h(F,C-F),void 0===B?B=F:(B+=String.fromCharCode(0),B+=F),F=C+e}Ec(r);return B},toWireType:function(r,y){"string"!=typeof y&&
T("Cannot pass non-string to C++ string type "+f);var A=q(y),B=nd(4+A+e);P[B>>2]=A>>t;l(y,B+4,A+e);null!==r&&r.push(Ec,B);return B},argPackAdvance:8,readValueFromPointer:Hb,ib:function(r){Ec(r)}})},E:function(a,e,f,h,l,q){Fb[a]={name:R(e),Fb:U(f,h),mb:U(l,q),Jb:[]}},g:function(a,e,f,h,l,q,w,t,r,y){Fb[a].Jb.push({Vb:R(e),$b:f,Yb:U(h,l),Zb:q,ic:w,hc:U(t,r),jc:y})},qa:function(a,e){e=R(e);Rb(a,{bc:!0,name:e,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},na:function(){return!0},
aa:function(){throw Infinity;},H:function(a,e,f){a=Lc(a);e=Nc(e,"emval::as");var h=[],l=wc(h);P[f>>2]=l;return e.toWireType(h,a)},M:function(a,e,f,h,l){a=Uc[a];e=Lc(e);f=Tc(f);var q=[];P[h>>2]=wc(q);return a(e,f,q,l)},z:function(a,e,f,h){a=Uc[a];e=Lc(e);f=Tc(f);a(e,f,null,h)},e:Kc,L:function(a){if(0===a)return wc(Vc());a=Tc(a);return wc(Vc()[a])},x:function(a,e){var f=Xc(a,e),h=f[0];e=h.name+"_$"+f.slice(1).map(function(w){return w.name}).join("_")+"$";var l=Yc[e];if(void 0!==l)return l;var q=Array(a-
1);l=Wc((w,t,r,y)=>{for(var A=0,B=0;B<a-1;++B)q[B]=f[B+1].readValueFromPointer(y+A),A+=f[B+1].argPackAdvance;w=w[t].apply(w,q);for(B=0;B<a-1;++B)f[B+1].Tb&&f[B+1].Tb(q[B]);if(!h.bc)return h.toWireType(r,w)});return Yc[e]=l},I:function(a,e){a=Lc(a);e=Lc(e);return wc(a[e])},r:function(a){4<a&&(Jc[a].Gb+=1)},Q:function(a,e,f,h){a=Lc(a);var l=$c[e];l||(l=Zc(e),$c[e]=l);return l(a,f,h)},J:function(){return wc([])},h:function(a){return wc(Tc(a))},C:function(){return wc({})},wa:function(a){a=Lc(a);return!a},
B:function(a){var e=Lc(a);Gb(e);Kc(a)},k:function(a,e,f){a=Lc(a);e=Lc(e);f=Lc(f);a[e]=f},j:function(a,e){a=Nc(a,"_emval_take_value");a=a.readValueFromPointer(e);return wc(a)},ca:function(){return-52},da:function(){},a:function(){Qa("")},ma:ad,ba:function(a){var e=K.length;a>>>=0;if(2147483648<a)return!1;for(var f=1;4>=f;f*=2){var h=e*(1+.2/f);h=Math.min(h,a+100663296);var l=Math;h=Math.max(a,h);l=l.min.call(l,2147483648,h+(65536-h%65536)%65536);a:{try{Ra.grow(l-eb.byteLength+65535>>>16);ib();var q=
1;break a}catch(w){}q=void 0}if(q)return!0}return!1},ea:function(a,e){var f=0;cd().forEach(function(h,l){var q=e+f;l=P[a+4*l>>2]=q;for(q=0;q<h.length;++q)fb[l++>>0]=h.charCodeAt(q);fb[l>>0]=0;f+=h.length+1});return 0},fa:function(a,e){var f=cd();P[a>>2]=f.length;var h=0;f.forEach(function(l){h+=l.length+1});P[e>>2]=h;return 0},ra:function(a){if(!noExitRuntime){if(p.onExit)p.onExit(a);Sa=!0}la(a,new Aa(a))},N:function(){return 52},Y:function(){return 52},ka:function(){return 52},Z:function(){return 70},
R:function(a,e,f,h){for(var l=0,q=0;q<f;q++){var w=P[e>>2],t=P[e+4>>2];e+=8;for(var r=0;r<t;r++){var y=K[w+r],A=ed[a];0===y||10===y?((1===a?La:Ka)(Ua(A,0)),A.length=0):A.push(y)}l+=t}P[h>>2]=l;return 0},c:function(){return Oa},l:od,s:pd,m:qd,K:rd,va:sd,X:td,W:ud,P:vd,p:wd,y:xd,n:yd,v:zd,ua:Ad,sa:Bd,ta:Cd,d:function(a){Oa=a},$:function(a,e,f,h){return jd(a,e,f,h)}};
(function(){function a(l){p.asm=l.exports;Ra=p.asm.xa;ib();jb=p.asm.Aa;lb.unshift(p.asm.ya);ob--;p.monitorRunDependencies&&p.monitorRunDependencies(ob);0==ob&&(null!==pb&&(clearInterval(pb),pb=null),qb&&(l=qb,qb=null,l()))}function e(l){a(l.instance)}function f(l){return Db().then(function(q){return WebAssembly.instantiate(q,h)}).then(function(q){return q}).then(l,function(q){Ka("failed to asynchronously prepare wasm: "+q);Qa(q)})}var h={a:Dd};ob++;p.monitorRunDependencies&&p.monitorRunDependencies(ob);
if(p.instantiateWasm)try{return p.instantiateWasm(h,a)}catch(l){return Ka("Module.instantiateWasm callback failed with error: "+l),!1}(function(){return Pa||"function"!=typeof WebAssembly.instantiateStreaming||zb()||Ab.startsWith("file://")||qa||"function"!=typeof fetch?f(e):fetch(Ab,{credentials:"same-origin"}).then(function(l){return WebAssembly.instantiateStreaming(l,h).then(e,function(q){Ka("wasm streaming compile failed: "+q);Ka("falling back to ArrayBuffer instantiation");return f(e)})})})().catch(da);
return{}})();p.___wasm_call_ctors=function(){return(p.___wasm_call_ctors=p.asm.ya).apply(null,arguments)};var nd=p._malloc=function(){return(nd=p._malloc=p.asm.za).apply(null,arguments)},Ec=p._free=function(){return(Ec=p._free=p.asm.Ba).apply(null,arguments)},Dc=p.___getTypeName=function(){return(Dc=p.___getTypeName=p.asm.Ca).apply(null,arguments)};p.___embind_register_native_and_builtin_types=function(){return(p.___embind_register_native_and_builtin_types=p.asm.Da).apply(null,arguments)};
var V=p._setThrew=function(){return(V=p._setThrew=p.asm.Ea).apply(null,arguments)},W=p.stackSave=function(){return(W=p.stackSave=p.asm.Fa).apply(null,arguments)},X=p.stackRestore=function(){return(X=p.stackRestore=p.asm.Ga).apply(null,arguments)};p.dynCall_viji=function(){return(p.dynCall_viji=p.asm.Ha).apply(null,arguments)};p.dynCall_vijiii=function(){return(p.dynCall_vijiii=p.asm.Ia).apply(null,arguments)};p.dynCall_viiiiij=function(){return(p.dynCall_viiiiij=p.asm.Ja).apply(null,arguments)};
p.dynCall_jiiiijiiiii=function(){return(p.dynCall_jiiiijiiiii=p.asm.Ka).apply(null,arguments)};p.dynCall_viiij=function(){return(p.dynCall_viiij=p.asm.La).apply(null,arguments)};p.dynCall_jiiiii=function(){return(p.dynCall_jiiiii=p.asm.Ma).apply(null,arguments)};p.dynCall_jiiiiii=function(){return(p.dynCall_jiiiiii=p.asm.Na).apply(null,arguments)};p.dynCall_jiiiiji=function(){return(p.dynCall_jiiiiji=p.asm.Oa).apply(null,arguments)};
p.dynCall_ji=function(){return(p.dynCall_ji=p.asm.Pa).apply(null,arguments)};p.dynCall_iijj=function(){return(p.dynCall_iijj=p.asm.Qa).apply(null,arguments)};p.dynCall_iiiji=function(){return(p.dynCall_iiiji=p.asm.Ra).apply(null,arguments)};p.dynCall_iiji=function(){return(p.dynCall_iiji=p.asm.Sa).apply(null,arguments)};p.dynCall_iijjiii=function(){return(p.dynCall_iijjiii=p.asm.Ta).apply(null,arguments)};p.dynCall_iij=function(){return(p.dynCall_iij=p.asm.Ua).apply(null,arguments)};
p.dynCall_vijjjii=function(){return(p.dynCall_vijjjii=p.asm.Va).apply(null,arguments)};p.dynCall_jiji=function(){return(p.dynCall_jiji=p.asm.Wa).apply(null,arguments)};p.dynCall_viijii=function(){return(p.dynCall_viijii=p.asm.Xa).apply(null,arguments)};p.dynCall_iiiiij=function(){return(p.dynCall_iiiiij=p.asm.Ya).apply(null,arguments)};p.dynCall_iiiiijj=function(){return(p.dynCall_iiiiijj=p.asm.Za).apply(null,arguments)};
p.dynCall_iiiiiijj=function(){return(p.dynCall_iiiiiijj=p.asm._a).apply(null,arguments)};function od(a,e){var f=W();try{return Q(a)(e)}catch(h){X(f);if(h!==h+0)throw h;V(1,0)}}function pd(a,e,f){var h=W();try{return Q(a)(e,f)}catch(l){X(h);if(l!==l+0)throw l;V(1,0)}}function yd(a,e,f,h){var l=W();try{Q(a)(e,f,h)}catch(q){X(l);if(q!==q+0)throw q;V(1,0)}}function qd(a,e,f,h){var l=W();try{return Q(a)(e,f,h)}catch(q){X(l);if(q!==q+0)throw q;V(1,0)}}
function wd(a,e){var f=W();try{Q(a)(e)}catch(h){X(f);if(h!==h+0)throw h;V(1,0)}}function sd(a,e,f,h,l,q){var w=W();try{return Q(a)(e,f,h,l,q)}catch(t){X(w);if(t!==t+0)throw t;V(1,0)}}function zd(a,e,f,h,l){var q=W();try{Q(a)(e,f,h,l)}catch(w){X(q);if(w!==w+0)throw w;V(1,0)}}function td(a,e,f,h,l,q,w){var t=W();try{return Q(a)(e,f,h,l,q,w)}catch(r){X(t);if(r!==r+0)throw r;V(1,0)}}function rd(a,e,f,h,l){var q=W();try{return Q(a)(e,f,h,l)}catch(w){X(q);if(w!==w+0)throw w;V(1,0)}}
function xd(a,e,f){var h=W();try{Q(a)(e,f)}catch(l){X(h);if(l!==l+0)throw l;V(1,0)}}function Ad(a,e,f,h,l,q){var w=W();try{Q(a)(e,f,h,l,q)}catch(t){X(w);if(t!==t+0)throw t;V(1,0)}}function Cd(a,e,f,h,l,q,w,t,r,y){var A=W();try{Q(a)(e,f,h,l,q,w,t,r,y)}catch(B){X(A);if(B!==B+0)throw B;V(1,0)}}function vd(a){var e=W();try{Q(a)()}catch(f){X(e);if(f!==f+0)throw f;V(1,0)}}function Bd(a,e,f,h,l,q,w){var t=W();try{Q(a)(e,f,h,l,q,w)}catch(r){X(t);if(r!==r+0)throw r;V(1,0)}}
function ud(a,e,f,h,l,q,w,t,r,y){var A=W();try{return Q(a)(e,f,h,l,q,w,t,r,y)}catch(B){X(A);if(B!==B+0)throw B;V(1,0)}}var Ed;function Aa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}qb=function Fd(){Ed||Gd();Ed||(qb=Fd)};
function Gd(){function a(){if(!Ed&&(Ed=!0,p.calledRun=!0,!Sa)){Eb(lb);ca(p);if(p.onRuntimeInitialized)p.onRuntimeInitialized();if(p.postRun)for("function"==typeof p.postRun&&(p.postRun=[p.postRun]);p.postRun.length;){var e=p.postRun.shift();mb.unshift(e)}Eb(mb)}}if(!(0<ob)){if(p.preRun)for("function"==typeof p.preRun&&(p.preRun=[p.preRun]);p.preRun.length;)nb();Eb(kb);0<ob||(p.setStatus?(p.setStatus("Running..."),setTimeout(function(){setTimeout(function(){p.setStatus("")},1);a()},1)):a())}}
p.run=Gd;if(p.preInit)for("function"==typeof p.preInit&&(p.preInit=[p.preInit]);0<p.preInit.length;)p.preInit.pop()();Gd();


  return CanvasKitInit.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = CanvasKitInit;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return CanvasKitInit; });
else if (typeof exports === 'object')
  exports["CanvasKitInit"] = CanvasKitInit;
