
/**
 * This file was generated by modulec.py from Cocoa Module Description XML file.
 * Never modify it manually. To regenerate this file, update XML file and rerun
 * modulec.py script.
 * Timestamp: 2022-11-29 23:15:59.285930
 */


#ifndef _COCOA_GALLIUM_BINDINGS_libtess2_H_ 
#define _COCOA_GALLIUM_BINDINGS_libtess2_H_

#include "Gallium/bindings/Base.h"
namespace cocoa::gallium::bindings {

cocoa::gallium::bindings::BindingBase *on_register_module_libtess2();

} // namespace libtess2

#endif // _COCOA_GALLIUM_BINDINGS_libtess2_H_
