
/**
 * This file was generated by modulec.py from Cocoa Module Description XML file.
 * Never modify it manually. To regenerate this file, update XML file and rerun
 * modulec.py script.
 * Timestamp: 2022-12-17 14:37:39.538224
 */


#ifndef _COCOA_GALLIUM_BINDINGS_cairo-embedder_H_ 
#define _COCOA_GALLIUM_BINDINGS_cairo-embedder_H_

#include "Gallium/bindings/Base.h"
namespace cocoa::gallium::bindings {

cocoa::gallium::bindings::BindingBase *on_register_module_cairo-embedder();

} // namespace cairo_embedder

#endif // _COCOA_GALLIUM_BINDINGS_cairo-embedder_H_
