#ifndef COCOA_GLAMOR_MOEINSTRUCTIONBASE_H
#define COCOA_GLAMOR_MOEINSTRUCTIONBASE_H

#include "Glamor/Glamor.h"
GLAMOR_NAMESPACE_BEGIN

using MoeOpcode = uint16_t;
using MoeVerb = uint8_t;

GLAMOR_NAMESPACE_END
#endif //COCOA_GLAMOR_MOEINSTRUCTIONBASE_H
