#ifndef COCOA_GLAMOR_MOE_MOEOPCODERENPYINTERFACE_H
#define COCOA_GLAMOR_MOE_MOEOPCODERENPYINTERFACE_H

#include "Glamor/Glamor.h"
GLAMOR_NAMESPACE_BEGIN

#include <RenpyMoeOpcodeCodeGen.h>

GLAMOR_NAMESPACE_END
#endif //COCOA_GLAMOR_MOE_MOEOPCODERENPYINTERFACE_H
